Create Create Your Own ERC-20 Token.md
hackclub/jams-bounty pull request #10
Opened 2023-06-24 10:07 UTC by briyandyju09

Name: **Briyan George Dyju**
slack: **briyandyju**

Do you run a club?
**No but I am pretty sure I'm really active** 😁

What relevant experiences do you have to help you write this Jam? 

**I have made many different tokens on many different networks such as Ethereum, Binance, Polygon networks. I am also very passionate about Fintech and Crypto.**

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam?

**Always! Feel free to message me no matter the time (ill message back at the earliest)**

2023-06-27 14:26 UTC, Arpan-206 requested changes
Some concerns regarding time estimation and customisability

2023-06-27 14:26 UTC, Arpan-206 commented on jams/Create Your Own ERC-20 Token.md
> +_Customization opportunity:_ Create you own coin with custom names, custom symbols, custom coin limits
We also need each app made during a Jam meeting to be functionally different, could you elaborate on how that'd be achieved?

2023-06-27 14:26 UTC, Arpan-206 commented on jams/Create Your Own ERC-20 Token.md
> +### Breakdown
Would you mind providing time estimations for each step?

2023-06-27 14:26 UTC, Arpan-206 commented on jams/Create Your Own ERC-20 Token.md
> +### -  Each token is unique in its own way with custom names and symbols and icons giving an unique feel.
This feels more like a style change rather than a functional change, so same query as in previous comment.

2023-06-27 14:33 UTC, briyandyju09 commented on jams/Create Your Own ERC-20 Token.md
> +_Customization opportunity:_ Create you own coin with custom names, custom symbols, custom coin limits
Each coin is unique in many ways, the people taking part can easily modify the code to have more coins in stock, or make the crypto for example; faster in transaction or less gas fees. The code is heavily modifiable and the Ethereum Blockchain is just an example. Students can easy make the same in matic, binance, flow, etc.

2023-06-27 14:40 UTC, briyandyju09 commented on jams/Create Your Own ERC-20 Token.md
> +### -  Each token is unique in its own way with custom names and symbols and icons giving an unique feel.
Replied in the first comment!

2023-06-27 14:44 UTC, briyandyju09 commented on jams/Create Your Own ERC-20 Token.md
> +### Breakdown
Alright!
Step 1 would take 10 to 15 mins as it depends on the person on how much time it takes to setup the accounts.

Step 2 would take 20 mins to 30 mins to understand the solidity programming language and writing a basic code.

Step 3 would only take 5 mins as deployment is fast. (Can depend on the Blockchain)

Hope this clears up things!

2023-06-27 14:46 UTC, Arpan-206 commented on jams/Create Your Own ERC-20 Token.md
> +_Customization opportunity:_ Create you own coin with custom names, custom symbols, custom coin limits
I kinda get it but would be better to seek another opinion on this, @sarthaktexas.

2023-06-27 14:46 UTC, Arpan-206 commented on jams/Create Your Own ERC-20 Token.md
> +### Breakdown
Can you add that to the file and make changes?

2023-06-27 14:47 UTC, briyandyju09 commented on jams/Create Your Own ERC-20 Token.md
> +### Breakdown
Sure!

2023-06-27 14:48 UTC, briyandyju09 commented on jams/Create Your Own ERC-20 Token.md
> +_Customization opportunity:_ Create you own coin with custom names, custom symbols, custom coin limits
What do you suggest? Create a crypto currency token has endless possibilities. It depends on what the person wants to use it for!

2023-06-27 14:49 UTC, briyandyju09 commented on jams/Create Your Own ERC-20 Token.md
> +### Breakdown
Added that part!

2023-06-29 14:31 UTC, sarthaktexas requested changes
I'm not going to leave too many specific comments, but I think this jam needs a bit of a rewrite. I really love the idea we talked about in DMs, but the title does not represent this idea and I was also a tiny bit confused by the whole proposal.

One element that I think you should include is using the coins with other club members and include time for doing that. That's the hook that I think this jam needs.

2023-06-29 14:31 UTC, sarthaktexas commented on jams/Create Your Own ERC-20 Token.md
> +- Part 2: Open remix IDE and write solidity code (its super easy that you can do it under 15 lines of code or less!)
what are the sub-parts for writing Solidity? Club members may not know how to write Solidity before this jam, and it will be helpful to see how you present this, more specifically.

2023-06-29 14:31 UTC, sarthaktexas commented on jams/Create Your Own ERC-20 Token.md
> +### - As the world progresses we are moving in a faster pace towards cryptocurrency and FinTech, by learning about current technologies Hackclubbers can be up to date with current trends.
This isn't really the answer we're looking for. One answer I can suggest would be talking about how they can use these coins in their club and with friends.

2023-06-29 14:31 UTC, sarthaktexas commented on jams/Create Your Own ERC-20 Token.md
> +### - Learning something new which is in your intrests always can turn out fun as by making something new you learn something new.
This also isn't really the type of answer we are looking for. I recommend writing about what they can make with this knowledge.

2023-06-29 14:31 UTC, sarthaktexas commented on jams/Create Your Own ERC-20 Token.md
> +### - As mentioned making your crypto is very customizable giving a sense of ownership.
This isn't what this question is asking, but I get what you meant. One answer could be sharing their coin with the club and providing a link (not sure if this is how it works). You would know better than me.

2023-06-30 09:35 UTC, briyandyju09 commented on jams/Create Your Own ERC-20 Token.md
> +- Part 2: Open remix IDE and write solidity code (its super easy that you can do it under 15 lines of code or less!)
I am going to start by explaining the important codes to get started with and give the example program.  By explaining the example program the members get an idea of how each line works. Solidity is fairly easy to grasp making this a perfect way to get started.

2023-06-30 09:57 UTC, briyandyju09 commented on jams/Create Your Own ERC-20 Token.md
> +### - As the world progresses we are moving in a faster pace towards cryptocurrency and FinTech, by learning about current technologies Hackclubbers can be up to date with current trends.
I have edited and made the necessary changes. Please review it once more!

2023-06-30 09:57 UTC, briyandyju09 commented on jams/Create Your Own ERC-20 Token.md
> +### - Learning something new which is in your intrests always can turn out fun as by making something new you learn something new.
Fixed that! Please review that part once more!

2023-06-30 09:58 UTC, briyandyju09 commented on jams/Create Your Own ERC-20 Token.md
> +### - As mentioned making your crypto is very customizable giving a sense of ownership.
Yup! Changed it.

2023-06-30 09:58 UTC, briyandyju09 commented on jams/Create Your Own ERC-20 Token.md
> +### - Learning something new which is in your intrests always can turn out fun as by making something new you learn something new.
Fixed that! Please review that part once more!

2023-06-30 09:58 UTC, briyandyju09 commented on jams/Create Your Own ERC-20 Token.md
> +### - As mentioned making your crypto is very customizable giving a sense of ownership.
Yup! Changed it.

2023-06-30 09:59 UTC, briyandyju09 commented
Hi @sarthaktexas! I made the necessary changes accordingly!

2023-06-30 13:54 UTC, sarthaktexas requested changes

2023-06-30 13:54 UTC, sarthaktexas commented on jams/Create Your Own ERC-20 Token.md
> +- Part 2: Open remix IDE and write solidity code (its super easy that you can do it under 15 lines of code or less!)
right, can you write down how you are going to present it?

2023-06-30 13:54 UTC, sarthaktexas commented on jams/Create Your Own ERC-20 Token.md
> +### Breakdown
I don't see this part in the file.

2023-06-30 13:55 UTC, sarthaktexas commented on jams/Create Your Own ERC-20 Token.md
> +### Breakdown
Oh I see it! Nevermind, can you put it adjacent to the actual step please?

2023-06-30 13:56 UTC, briyandyju09 commented on jams/Create Your Own ERC-20 Token.md
> +### Breakdown
It's right after the steps?

2023-06-30 14:09 UTC, Arpan-206 approved these changes
LGTM!

2023-06-30 14:11 UTC, sarthaktexas approved these changes
thanks!

2023-06-30 14:11 UTC, sarthaktexas commented on jams/Create Your Own ERC-20 Token.md
> +- Understanding Solidity: going to start by explaining the code, showing some examples and going through the example code line by line to ensure that the code is easy to follow.
cool thanks!

2023-06-30 14:13 UTC, briyandyju09 commented
Let go! Thanks so much guys!

2023-06-30 14:32 UTC, faisalsayed10 commented on jams/Create Your Own ERC-20 Token.md
> +### -  Each token is unique in its own way with custom names, symbols, and icons, giving a unique feel. The systems of each project, such as the blockchains they work on, contracts they use, and code
how difficult would it be for club members to use a different blockchain and still follow your guide? or would you be providing examples at places for how a particular task would be done in another blockchain? (My thought process while asking this question is that each blockchain is technically different and would require a lot of changes in the code, correct me if I'm wrong)

2023-06-30 14:40 UTC, Arpan-206 commented on jams/Create Your Own ERC-20 Token.md
> +### -  Each token is unique in its own way with custom names, symbols, and icons, giving a unique feel. The systems of each project, such as the blockchains they work on, contracts they use, and code
Not OP obviously but I think it should be pretty much the same on all Ethereum powered or Ethereum like blockchains. On other chains however, it may be drastically different and won't be too easy to cover in a single jam.

2023-06-30 14:49 UTC, briyandyju09 commented on jams/Create Your Own ERC-20 Token.md
> +### -  Each token is unique in its own way with custom names, symbols, and icons, giving a unique feel. The systems of each project, such as the blockchains they work on, contracts they use, and code
The only thing they have to change drastically is the node they work on and a contract they ca source of online. It's relatively easy and I would be able to cover some simple steps in a slide.

2023-06-30 14:50 UTC, briyandyju09 commented on jams/Create Your Own ERC-20 Token.md
> +### -  Each token is unique in its own way with custom names, symbols, and icons, giving a unique feel. The systems of each project, such as the blockchains they work on, contracts they use, and code
And yes, using Ethereum and following the guide might be easier and the other chains can be kept as a challenge. As for the code, most of it remains other than the contract.

2023-06-30 14:51 UTC, briyandyju09 commented on jams/Create Your Own ERC-20 Token.md
> +### -  Each token is unique in its own way with custom names, symbols, and icons, giving a unique feel. The systems of each project, such as the blockchains they work on, contracts they use, and code
Hope this helps @faisalsayed10!

2023-06-30 15:01 UTC, faisalsayed10 commented on jams/Create Your Own ERC-20 Token.md
> +### -  Each token is unique in its own way with custom names, symbols, and icons, giving a unique feel. The systems of each project, such as the blockchains they work on, contracts they use, and code
Oh that makes sense, all good!

2023-06-30 15:01 UTC, faisalsayed10 approved these changes
LGTM

2023-06-30 15:06 UTC, merged

2023-06-30 15:07 UTC, briyandyju09 commented
Let's go! Merged already?

2023-06-30 15:09 UTC, SerenityUX commented
This is quite cool. Will Hack Clubbers be able to create as much of their coin as they want and share it with each other (maybe in club meets)?

Club currency of some sort?

2023-06-30 15:13 UTC, Arpan-206 commented
> This is quite cool. Will Hack Clubbers be able to create as much of their coin as they want and share it with each other (maybe in club meets)?
> 
> Club currency of some sort?

Again not OP, but yes to both.

(Source Slack DM and personal experience)

2023-07-01 07:08 UTC, briyandyju09 commented
Yes they can!