Zero To Crypto-Hero: Creating a simple secret note machine
hackclub/jams-bounty pull request #11
Opened 2023-06-24 10:45 UTC by cfanoulis

Name: Charalampos Fanoulis

Do you run a club? - No but I believe I qualify as an active member

What relevant experiences do you have to help you write this Jam? - Fromerly headed Hackropolis, have previously written a workshop, I have used JS for a while now

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam? - Yes!!

2023-06-27 13:13 UTC, sarthaktexas requested changes
requested changes in the last comment :)

2023-06-27 13:13 UTC, sarthaktexas commented on jams/zero-to-crypto-hero.md
> +- How will you ensure that every outcome of the workshop varies (i.e. how will you give jammers a sense of ownership over their project)? - See customization opportunities. The implemented algorithm
okay, i like this! it's pretty simple

2023-06-27 13:13 UTC, sarthaktexas commented on jams/zero-to-crypto-hero.md
> +  - Preamble is being presented by the leader while setup is being done
only a greek person would write the word preamble

2023-06-27 13:13 UTC, sarthaktexas commented on jams/zero-to-crypto-hero.md
> +- How will you allow Club Leaders to add their own project to the Jam presentation (giving them a sense of ownership over the meeting)? - At the end, we can include other successful or innnovative al
I don't like this part. I like what line 30 says, that should be the answer to this question imo.

2023-06-27 14:26 UTC, cfanoulis commented on jams/zero-to-crypto-hero.md
> +- How will you allow Club Leaders to add their own project to the Jam presentation (giving them a sense of ownership over the meeting)? - At the end, we can include other successful or innnovative al
I actually don't understand this; is this supposed to allow club leaders to evlove the jam and share it onwards or just each jam leader can personalize it for their club

2023-06-27 14:26 UTC, cfanoulis commented on jams/zero-to-crypto-hero.md
> +  - Preamble is being presented by the leader while setup is being done
it was late at night and english wouldnt english

2023-06-29 15:19 UTC, sarthaktexas reviewed
I think this is really cool as a workshop, but thinking through this I don't think there is opportunity for customization anywhere and therefore not a jam. Please correct me if you disagree, however. Char, you can slack me, and we can hop on a zoom call to brainstorm if you would like.

2023-06-29 15:20 UTC, sarthaktexas commented on jams/zero-to-crypto-hero.md
> +- How will you allow Club Leaders to add their own project to the Jam presentation (giving them a sense of ownership over the meeting)? - At the end, we can include other successful or innnovative al
If you still have this question, slack me Char.

2023-06-30 08:27 UTC, closed without merging