Main2
hackclub/jams-bounty pull request #14
Opened 2023-06-24 17:15 UTC by JackTDC

Thanks for making a PR! Please fill in the below:

Name:

Do you run a club? 
- We ran a club 2 years ago but it has since been dispersed.

What relevant experiences do you have to help you write this Jam?
- I made a workshop in the last workshop bounty too heres the link : https://workshops.hackclub.com/rock_paper_scissors/
- Further more I had involvement in SOM too where I made a fingerprint attendance system with the parts provided to me by HC

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam?
- Of course! Anytime.

2023-06-26 14:23 UTC, sarthaktexas reviewed
This resonates with me because it's how I first got into Javascript (I used `discord.js`) but I really like this jam because there are endless possibilities for customization.

2023-06-26 14:23 UTC, sarthaktexas commented on jams/Discord_Bot.md
> +- Part 3: Giving the bot a voice!
I don't think it is possible to do Parts 3 and 4 in the same club meeting as Parts 1 and 2. I love this idea though! Can you possibly write two different breakdowns for two different club sessions? I'll bring this up with the team and how they feel about it. Thanks!

2023-06-26 14:23 UTC, sarthaktexas commented on jams/Discord_Bot.md
> +- Part 4: Creating a webserver for the bot
What exactly does this mean? Is this a specific `discord.py` thing? I've never seen this in `discord.js`. Just curious, thanks!

2023-06-26 14:24 UTC, sarthaktexas commented
I'm not marking as needs changes, because I'm not sure about that yet, but mark this as ready to review when you're done with that change!

2023-06-26 14:32 UTC, cfanoulis commented on jams/Discord_Bot.md
> +- Part 4: Creating a webserver for the bot
fwiw: bots in discord now work similarly to how bots in slack work, using a web endpoint discord posts to instead of a websocket

2023-06-26 15:58 UTC, JackTDC commented on jams/Discord_Bot.md
> +- Part 4: Creating a webserver for the bot
By webserver i mean keeping the bot online 24/7, you can just copy the replit link and post it on UpTimeRobot and it just ping that website after every 5 mins(changeable) and thus you can keep the bot online even after you close ur pc and for free

2023-06-26 16:02 UTC, JackTDC commented on jams/Discord_Bot.md
> +- Part 3: Giving the bot a voice!
Part 4 is a must to keep the bot always active, but I do get how part 3 could be time consuming. I will divide it into 2 sessions let me know what the team says, there are lot of other things I could add instead so if you want me to just have 1 session, I will add something more simple.

2023-06-27 13:02 UTC, sarthaktexas commented on jams/Discord_Bot.md
> +- Part 4: Creating a webserver for the bot
Yeah I was confused at first too @cfanoulis

2023-06-27 13:03 UTC, sarthaktexas commented on jams/Discord_Bot.md
> +- Part 3: Giving the bot a voice!
I think adding that at the end as not part of the jam is great. But yeah let's keep this in one session and remove the music part for now, thanks!

2023-06-27 13:03 UTC, sarthaktexas requested changes
just fix the comment i left above and you're golden

2023-06-27 13:19 UTC, JackTDC commented on jams/Discord_Bot.md
> +- Part 3: Giving the bot a voice!
Alright, works for me!

2023-06-27 14:41 UTC, Arpan-206 reviewed
Just a minor enhancement, otherwise fantastic idea!

2023-06-27 14:41 UTC, Arpan-206 commented on jams/Discord_Bot.md
> +### Breakdown
I think time estimates for each step would be very helpful.

2023-06-27 15:35 UTC, JackTDC commented on jams/Discord_Bot.md
> +### Breakdown
On it!

2023-06-27 15:38 UTC, JackTDC commented on jams/Discord_Bot.md
> +### Breakdown
@Arpan-206, Added time estimate. Should be good now right?

2023-06-27 15:40 UTC, Arpan-206 approved these changes

2023-06-27 15:40 UTC, Arpan-206 commented on jams/Discord_Bot.md
> +### Breakdown
Yep, perfect!

2023-06-27 17:48 UTC, linkai101 reviewed
I'm definitely loving this idea! I think that there should be a discord.js version of this as well, though, since its not deprecated and thus has better support for new discord features (buttons, menus, slash commands, etc.) and can reach more people familiar with js.

2023-06-27 18:40 UTC, cytronicoder commented
I can follow-up with a `discord.js` version! @linkai101

2023-06-28 07:55 UTC, JackTDC commented
@linkai101 that's such a cool idea, what if we just had like a button on the website which when pressed just changed the language the Jam is using. So it would be easier for coders!

2023-06-28 07:57 UTC, Arpan-206 commented
> @linkai101 that's such a cool idea, what if we just had like a button on the website which when pressed just changed the language the Jam is using. So it would be easier for coders!

I love this idea, what do you think @SerenityUX?

2023-06-28 08:09 UTC, JackTDC commented
I am willing to spend my time and make the jam through both the languages, just let me know what you'll decide !

2023-06-28 11:46 UTC, zeyuyaoy commented
Yes that would be really cool 👍

2023-06-28 13:34 UTC, JackTDC commented
@cytronicoder do you want to help, we could perhaps work on it together ?

2023-06-29 15:26 UTC, sarthaktexas approved these changes

2023-06-29 15:26 UTC, sarthaktexas commented
I'm approving, I have no more comments. Thanks!

2023-06-29 16:45 UTC, linkai101 approved these changes
Oops, I commented instead of reviewed. LGTM!, and there's plenty room for future sessions/customizability like slash commands and other Discord features.

I would advise for Discord bots though that things change fast since Discord is adding/changing things all the time. Love this idea.

2023-06-29 17:09 UTC, zeyuyaoy commented
> @cytronicoder do you want to help, we could perhaps work on it together ? 

Definitely!!

2023-06-30 00:39 UTC, sarthaktexas requested changes
Wait a minute is this not missing the questions at the bottom?

2023-07-01 12:54 UTC, JackTDC commented
@sarthaktexas any more changes I should do?

2023-07-10 17:26 UTC, sahitid commented
i'm sorry! this jams replicates an already existing workshop for making a discord bot. i'm sorry, but i don't think we will be accepting this as a bounty.

2023-07-10 17:26 UTC, closed without merging