Create Voxel_Animation.md
hackclub/jams-bounty pull request #15
Opened 2023-06-24 18:17 UTC by GalaxyGamingBoy

Thanks for making a PR! Please fill in the below:

Name: Marios Mitsios

Do you run a club? 
No but I believe I am an active member of the community.

What relevant experiences do you have to help you write this Jam?
I have experience with game development and Three JS in general.

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam?
Yes, of course!

2023-06-27 14:01 UTC, sarthaktexas requested changes

2023-06-27 14:01 UTC, sarthaktexas commented on jams/Voxel_Animation.md
> + - Part 4: Create the map that the animation will live in
how long does this take, can you provide a time estimate for each part? additionally, can you provide an example final project, i'm a bit unsure what this results in. thanks!

2023-06-27 14:05 UTC, GalaxyGamingBoy commented
@sarthaktexas Yes of course, I will share a replit project my final outcome

2023-06-27 14:08 UTC, Arpan-206 commented on jams/Voxel_Animation.md
> + - Part 4: Create the map that the animation will live in
+1 on this.

2023-06-27 14:13 UTC, Arpan-206 requested changes
I feel like this project is great but won't fit very well in the given time constraint.

2023-06-27 14:13 UTC, Arpan-206 commented on jams/Voxel_Animation.md
> + - Part 4: Create the map that the animation will live in
Also, as far as I'm aware, this level of animation with ThreeJS can take a lot more time than an hour especially for beginners.

2023-06-27 15:53 UTC, GalaxyGamingBoy commented on jams/Voxel_Animation.md
> + - Part 4: Create the map that the animation will live in
@Arpan-206 I am thinking more like recording a simple house that opens it's door. Something really simple

2023-06-27 15:53 UTC, GalaxyGamingBoy commented on jams/Voxel_Animation.md
> + - Part 4: Create the map that the animation will live in
For more advanced animations we could split it into 2 sessions

2023-06-27 16:02 UTC, GalaxyGamingBoy commented
Since it would be specifically a voxel only scene, the code needed is pretty simple.
`const cube = new THREE.Mesh(new THREE.BoxGeometry( 1, 1, 1), material);`
`scene.add(cube)`
That is how to add one cube, With the ability to resize it also is less time consuming to create things like walls

2023-06-27 16:03 UTC, GalaxyGamingBoy commented
Less than 20 Minute demo can be found here: https://replit.com/@GalaxyGamingBoy/HCJam

2023-06-27 16:06 UTC, GalaxyGamingBoy commented
If needed we can also cut the animation recorder to save a bit of time, since the main focus is creating it

2023-06-27 16:26 UTC, Arpan-206 commented on jams/Voxel_Animation.md
> + - Part 4: Create the map that the animation will live in
Got it!

But I can't see this being very customisable, could you describe what each person following through could do differently so that they don't end up with the same product?

2023-06-27 16:46 UTC, GalaxyGamingBoy commented on jams/Voxel_Animation.md
> + - Part 4: Create the map that the animation will live in
Yep! So:
Each person would be encouraged to create a unique animation that is totally different to each other. The club leader would encourage each member to do something unique and even wacky! Each member could thing of a basic animation idea to create or the leader can have a "pool of idea" that members are encouraged to use but it will have a system in place to allow one idea per person. Furthermore for the people that also need a creative boost we can link some "animation idea generators" that generate totally random ideas! ( Note: They would have to take it a notch down ). The leader will also encourage simplicity as to not waste that much time on details but the animation itself to make it fun. At the end the animation should be something simple. Some ideas that come to mind are:

- Simple house animation
- A rectangle earth with "meteors" coming down to it
- A stable name with the camera zooming out
- A cube that expands
Thoughts? @Arpan-206? I really want to create this jam and it seems quite feasible to create

2023-06-27 17:52 UTC, GalaxyGamingBoy commented
Okay just returned to home, pushed the changes

2023-06-28 02:39 UTC, Arpan-206 commented on jams/Voxel_Animation.md
> +  Each person would be encouraged to create a unique animation that is totally different to each other. The club leader would encourage each member to do something unique and even wacky! Each member
I still have concerns on leaving a lot of the customisability on the leader.

What do you think @sarthaktexas?

2023-06-28 06:07 UTC, GalaxyGamingBoy commented on jams/Voxel_Animation.md
> +  Each person would be encouraged to create a unique animation that is totally different to each other. The club leader would encourage each member to do something unique and even wacky! Each member
@Arpan-206 Hmmmmm At that case I can provide a few pools of different ideas so they are pre reviewed and are safe and simple so they will be 100% doable on the time constraints

2023-06-28 15:24 UTC, GalaxyGamingBoy commented
@Arpan-206 Can you review the latest answer?

2023-06-28 15:28 UTC, Arpan-206 approved these changes

2023-06-28 15:28 UTC, Arpan-206 commented on jams/Voxel_Animation.md
> +  Each person would be encouraged to create a unique animation that is totally different to each other, animations can be fun or even wacky! Each member could think of a basic animation idea to creat
Looks good to me!

2023-06-29 14:34 UTC, sarthaktexas commented on jams/Voxel_Animation.md
> +  Each person would be encouraged to create a unique animation that is totally different to each other. The club leader would encourage each member to do something unique and even wacky! Each member
Let me resolve this and create a new comment thread, but I agree with Arpan here.

2023-06-29 14:35 UTC, sarthaktexas commented on jams/Voxel_Animation.md
> +  Each person would be encouraged to create a unique animation that is totally different to each other, animations can be fun or even wacky! Each member could think of a basic animation idea to creat
lgtm as well!

2023-06-29 14:40 UTC, sarthaktexas approved these changes

2023-06-29 17:18 UTC, faisalsayed10 approved these changes
LGTM

2023-06-30 00:35 UTC, merged