Create Introduction To Using APIs in Python.md
hackclub/jams-bounty pull request #17
Opened 2023-06-25 01:52 UTC by bulkypanda

Thanks for making a PR! Please fill in the below:

Name: Arya Gummadi

Do you run a club? Used To. Just Graduated

What relevant experiences do you have to help you write this Jam? Built successful discord bots (several API use cases) with over 10k users, created a project that uses Spotify API to create a family-friendly version of the selected playlist etc.

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam? Yes, anytime.

2023-06-27 14:28 UTC, sarthaktexas requested changes
Great start, needs some improvement.

2023-06-27 14:28 UTC, sarthaktexas commented on jams/Introduction To Using APIs in Python.md
> +_Customization opportunity:_ You can build any project using APIs in Python. You can use any API of your choice. Example: A project that uses the Twitter API to post tweets, a project that uses the G
I love this. How will you present this and allow them to do this during your club meeting? Will you provide a list of API's? Spotify is a bad example because it requires auth, can you think of and write down some others?

2023-06-27 14:28 UTC, sarthaktexas commented on jams/Introduction To Using APIs in Python.md
> +_Platform Limitations:_ Browser-based Replit Development, Local Machine with Python Installed
This much be browser-based completely, a local machine doesn't work for students with just a chromebook.

2023-06-27 14:28 UTC, sarthaktexas commented on jams/Introduction To Using APIs in Python.md
> +- Part 1: Setup an API key with a dictionary website and get the API key
Since everyone will be doing something different, is there a different way to present this?

2023-06-27 14:28 UTC, sarthaktexas commented on jams/Introduction To Using APIs in Python.md
> +### - Introduce to them the idea of APIs, how commonly they're used and how they can be used to build cool projects of any sort and interact with websites of their choice.
this doesn't answer the question. what specific parts can be customized?

2023-06-27 14:28 UTC, sarthaktexas commented on jams/Introduction To Using APIs in Python.md
> +### - APIs are used everywhere. They are used to interact with websites, create projects, automate tasks etc. They are very useful and can be used to build cool projects.
this doesn't answer the question. what is the personal aspect of this project?

2023-06-27 14:28 UTC, sarthaktexas commented on jams/Introduction To Using APIs in Python.md
> +### - Setup project, API key, write code to fetch and parse data.
can i get an outline for the slides and a time estimation for each?

2023-06-27 14:28 UTC, sarthaktexas commented on jams/Introduction To Using APIs in Python.md
> +### - Browser-based Replit Development, Any Local Machine with Python Installed, No Mobile Devices
we can't do local machines. look above.

2023-06-27 14:28 UTC, sarthaktexas commented on jams/Introduction To Using APIs in Python.md
> +### - Club Leaders can build anything of their choice due to the possiblities of customization. They can interact with Spotify, News Sources, GitHub etc. We can also include interesting and successfu
Again, how will you present this customization part in the jam?

2023-06-27 14:38 UTC, Arpan-206 requested changes
+1 on all points by @sarthaktexas and also how is this more of a Jam (project based) than a tutorial or a Crash course.

2023-06-27 14:38 UTC, Arpan-206 commented on jams/Introduction To Using APIs in Python.md
> +_Customization opportunity:_ You can build any project using APIs in Python. You can use any API of your choice. Example: A project that uses the Twitter API to post tweets, a project that uses the G
I can't see how this is a project more than a tutorial or a crash course to be honest.

2023-06-27 14:38 UTC, Arpan-206 commented on jams/Introduction To Using APIs in Python.md
> +### - Introduce to them the idea of APIs, how commonly they're used and how they can be used to build cool projects of any sort and interact with websites of their choice.
+1

2023-06-27 15:04 UTC, bulkypanda commented on jams/Introduction To Using APIs in Python.md
> +_Customization opportunity:_ You can build any project using APIs in Python. You can use any API of your choice. Example: A project that uses the Twitter API to post tweets, a project that uses the G
Thank you for your comment, @Arpan-206. While it may seem like a tutorial or crash course at first glance, this project goes beyond that by allowing individuals to apply their knowledge and skills practically and creatively.

By building a project using APIs in Python, jammers can leverage real-world data and functionalities to create unique applications. They can integrate with popular platforms and services like Twitter, Google Maps, Spotify, and others to develop innovative solutions tailored to their specific needs.

Projects like these provide hands-on experience in working with APIs, handling data, and building applications that can be used in various domains. They encourage problem-solving, critical thinking, and creativity, as users can choose the APIs they want to work with and design projects that align with their interests.

Moreover, building a project using APIs in Python allows jammers to understand the concepts of web development, API authentication, data retrieval, data manipulation, and more. These valuable skills can be applied in professional settings or personal projects.

So, while this project does involve learning and exploring APIs, it offers the opportunity to create something practical and meaningful. It enables users to showcase their abilities and opens doors to endless possibilities regarding what they can achieve.

I hope this helps clear up how this project goes beyond a simple tutorial or crash course. If you have any specific questions or suggestions, please let me know. I'm here to answer anything else!

2023-06-27 15:19 UTC, Arpan-206 commented on jams/Introduction To Using APIs in Python.md
> +_Customization opportunity:_ You can build any project using APIs in Python. You can use any API of your choice. Example: A project that uses the Twitter API to post tweets, a project that uses the G
I do get your point, however, we are looking for end products that are ready to be used at the end of the workshop, I'm not super sure if something like this (something you **can** use to build on qualifies as a ready to use project, to me, it seems more of an intermediate in the process of building something.

2023-06-29 15:06 UTC, sarthaktexas requested changes
I'm still confused how you're running this jam? Can you make it more clear by talking about how you will allow freedom of which API they use and still make your jam go smoothly? Thanks!

2023-06-29 15:06 UTC, sarthaktexas commented on jams/Introduction To Using APIs in Python.md
> +_Customization opportunity:_ You can build any project using APIs in Python. You can use any API of your choice. Example: A project that uses the Twitter API to post tweets, a project that uses the G
so I don't think you should talk about one specific API, probably give them freedom with any one they want.

2023-06-29 15:06 UTC, sarthaktexas commented on jams/Introduction To Using APIs in Python.md
> +- Part 1: Setup an API key with a website of your choice and get the API key
this does not match your introduction

2023-06-30 02:55 UTC, Arpan-206 commented on jams/Introduction To Using APIs in Python.md
> +- Part 1: Setup an API key with a website of your choice and get the API key
I think it does now

2023-06-30 02:55 UTC, Arpan-206 approved these changes
LGTM!

2023-06-30 16:38 UTC, bulkypanda commented
> I'm still confused how you're running this jam? Can you make it more clear by talking about how you will allow freedom of which API they use and still make your jam go smoothly? Thanks!

@sarthaktexas ,

Participants are free to choose any API they wish to work with. The goal is to encourage creativity and learning through exploration. As long as the API is publicly accessible and can be used without infringing on any terms of service, it's allowed.

To ensure the jam runs smoothly, we'll have a set of guidelines and resources available to help participants who might run into trouble. This includes basic tutorials on how to use APIs, troubleshooting tips, and more.

2023-07-07 19:35 UTC, bulkypanda commented
@sarthaktexas any update?

2023-07-10 17:38 UTC, sarthaktexas approved these changes

2023-07-10 17:41 UTC, sarthaktexas commented
since i'm still a bit clear on the execution of this and what a final project might look like, i don't think we can accept this jam. thank you for the proposal and i'm sorry for this outcome!

2023-07-10 17:41 UTC, closed without merging