Add Kaboom jam
hackclub/jams-bounty pull request #18
Opened 2023-06-25 04:08 UTC by ajs256

Thanks for making a PR! Please fill in the below:

Name: Alex S (\@alex on Slack. Find me in #alexs-adhd-something

Do you run a club? No, but I am active in the Hack Club community.

What relevant experiences do you have to help you write this Jam?
I have done a lot of basic JS work before, including with Sprig. To be honest, I haven't used Kaboom before, but I learn best by teaching!

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam?
Of course, I'd love to help people out!

2023-06-26 14:28 UTC, sarthaktexas reviewed
yeah, I have no changes for your proposal. I would say that I'm not sure this can be done in the time you said, but I have no experience with this, so I'll take your word on that. If you could answer my question in the comment, that would be helpful because I'm a bit unsure about how they know/learn how to code in JS.

2023-06-26 14:28 UTC, sarthaktexas commented on jams/build_a_game.md
> +- Let the Jammers go wild for the rest of the workshop time!
Love this

2023-06-26 14:28 UTC, sarthaktexas commented on jams/build_a_game.md
> +I will not say that This Is The Level/Sprite You Should Create, and show multiple examples.
Love this

2023-06-26 14:28 UTC, sarthaktexas commented on jams/build_a_game.md
> +- How to use basic JS
Will you show them how to code functions?

2023-06-26 14:28 UTC, sarthaktexas commented on jams/build_a_game.md
> +#### How will you allow Club Leaders to add their own project to the Jam presentation (giving them a sense of ownership over the meeting)?
Love this

2023-06-26 16:13 UTC, ajsirota commented on jams/build_a_game.md
> +- How to use basic JS
I'll use arrow functions mostly, since most of Kaboom's examples use them. Maybe I'll include it as a side note.

2023-06-27 01:24 UTC, ajsirota commented on jams/build_a_game.md
> +- How to use basic JS
@sarthaktexas do you think there's something else that needs to be mentioned?

2023-06-27 13:17 UTC, sarthaktexas commented on jams/build_a_game.md
> +- How to use basic JS
okay, i think you should have a little side quest for functions if that makes sense?

2023-06-27 13:18 UTC, sarthaktexas commented on jams/build_a_game.md
> +- How to use basic JS
but overall this looks great, if you don't want to make this change that's fine imo

2023-06-27 13:54 UTC, Arpan-206 requested changes
I just have a few concerns regarding time estimations.

2023-06-27 13:54 UTC, Arpan-206 commented on jams/build_a_game.md
> +### Breakdown
Would you mind adding time required for individual steps? It will help us get a better idea of how feasible it is, and better cross-check the time estimations on our end.

Something like this should so the job
```
- Part 1: Remix a template I will make (15 mins) 
```

2023-06-27 13:54 UTC, Arpan-206 commented on jams/build_a_game.md
> +_Time estimation:_ 30 minutes to 1 hour
I think this range is too big, 30 mins. Could you narrow it down to something like 40-50 mins for example.

2023-06-27 17:43 UTC, Arpan-206 approved these changes
Looks good!

2023-06-29 15:28 UTC, sarthaktexas approved these changes
No more comments from me, approved! Looking forward to this one.

2023-06-29 17:05 UTC, faisalsayed10 approved these changes

2023-06-29 17:05 UTC, faisalsayed10 commented on jams/build_a_game.md
> +1. What are we going to make?
Love this jam! Just this point seems a bit confusing to me.

2023-06-29 18:27 UTC, ajsirota commented on jams/build_a_game.md
> +1. What are we going to make?
Line 29 can be worded as "I will make sure to be open in what I suggest Jammers to do, and not pigeonhole everyone into one of a few paths".

2023-06-29 18:31 UTC, faisalsayed10 commented on jams/build_a_game.md
> +1. What are we going to make?
Oh I mean line 32

2023-06-29 18:33 UTC, ajsirota commented on jams/build_a_game.md
> +1. What are we going to make?
That's saying "intro the project, demo one possible end result"

2023-06-30 00:33 UTC, merged