BASH 101
hackclub/jams-bounty pull request #20
Opened 2023-06-26 19:45 UTC by ZeroQLi

Name: Mohammed Eshan

Do you run a club?
No, but i am an active member.

What relevant experiences do you have to help you write this Jam?
As a Window managers enthuisast, i regurlarly write and use scripts to speed up my productivity and time. I believe using the terminal is a surefire way of completing work faster than GUI's

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam?
Yes

2023-06-27 14:19 UTC, Arpan-206 requested changes
Idea is very good but feels like more of a tutorial imo, so suggested some changes pertaining to that.

2023-06-27 14:19 UTC, Arpan-206 commented on jams/bash101.md
> +_Outcome:_ Learn the BASH scripting language by creating a simple timezone converter.
I think the goal of Jams is a lot more focus on building a project rather than a tutorial, so could you change the title (and moreover the PR to reflect that)

2023-06-27 14:19 UTC, Arpan-206 commented on jams/bash101.md
> +### Breakdown (TBD)
Can you put time estimations for individual steps?

2023-06-27 14:19 UTC, Arpan-206 commented on jams/bash101.md
> +_Customization opportunity:_ Different usecases and commands.
Can you elaborate more on this, more so on how each Jam will be different at the end of the meeting?

2023-06-27 14:20 UTC, sarthaktexas commented
Echoing everything Arpan said.

2023-06-27 14:22 UTC, sarthaktexas requested changes
This is incomplete, but I have a couple comments as well.

2023-06-27 14:22 UTC, sarthaktexas commented on jams/bash101.md
> +- Any linux based OS (including chromeos and MACOS)
Could you possibly make this be done on Repl.it?

2023-06-27 14:22 UTC, sarthaktexas commented on jams/bash101.md
> +- PART 4:
Where are the rest of the questions?

2023-06-27 14:28 UTC, Arpan-206 commented on jams/bash101.md
> +- PART 4:
Yeah, I was wondering too but forgot to comment that.

2023-06-28 14:59 UTC, ZeroQLi commented
closing as i've realized there's not much room for cuztomization, back to the drawing board

2023-06-28 14:59 UTC, closed without merging