cinder.md
hackclub/jams-bounty pull request #22
Opened 2023-06-27 17:43 UTC by euphorichubbbb

Thanks for making a PR! Please fill in the below:

Name: Euphoric3hub

Do you run a club? 
no, I believe that you believe me as an active member

What relevant experiences do you have to help you write this Jam?

I had learnt cinder in a same type of workshop in my school, and even used it to make some motion graphics for some small funny charactor 

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam?
Yes

2023-06-27 17:49 UTC, sarthaktexas reviewed
This isn't web-based, and cannot be done on Chromebooks.

2023-06-28 03:37 UTC, euphorichubbbb commented
> This isn't web-based, and cannot be done on Chromebooks.

I think we can use https://p5js.org/ (P5.js)

2023-06-28 06:20 UTC, Arpan-206 commented
If you want to use p5js, make the necessary changes in the PR (Preferable make a new PR)

2023-06-28 11:40 UTC, Arpan-206 requested changes

2023-06-28 11:40 UTC, Arpan-206 commented on Visual Experiences with p5.js.md
> +### Breakdown
Would you mind providing time estimations for each step?

2023-06-28 13:41 UTC, euphorichubbbb commented on Visual Experiences with p5.js.md
> +### Breakdown
hey I mentioned it in the PR

2023-06-28 13:44 UTC, Arpan-206 commented on Visual Experiences with p5.js.md
> +### Breakdown
I was saying about adding something like time estimation for each of the steps

2023-06-28 13:45 UTC, Arpan-206 commented on Visual Experiences with p5.js.md
> +### Breakdown
Just saw it nvm

Looks good!

2023-06-28 15:19 UTC, Arpan-206 approved these changes
LGTM!

2023-06-29 13:50 UTC, jianmin-chen approved these changes

2023-06-29 15:37 UTC, sarthaktexas requested changes
Am I tripping or did we not talk about changing this to use p5 on the web. Just write it so that it focuses on doing it on a web platform, and change the breakdown section to reflect this.

2023-06-29 15:37 UTC, sarthaktexas commented on Visual Experiences with p5.js.md
> +- **Requirements:** Computer with p5.js library installed
web-based remember

2023-06-29 15:37 UTC, sarthaktexas commented on Visual Experiences with p5.js.md
> +- **Platform Limitations:** Windows, macOS, Linux, and web browsers
just put none haha

2023-06-29 16:23 UTC, linkai101 requested changes
I really resonate with this jam idea -- my very first experience with code was with Processing.js on Khan Academy and stuff like this is awesome. Visual coding is imo the best way to learn to code and I could imagine hack clubbers loving this.

2023-06-29 16:23 UTC, linkai101 commented on Visual Experiences with p5.js.md
> +- **Requirements:** Computer with p5.js library installed
p5.js can be imported simply with a script tag with a cdn or a local downloaded file -- this is web based but maybe change wording

2023-06-29 16:23 UTC, linkai101 commented on Visual Experiences with p5.js.md
> +2. **Part 1:** Understanding the p5.js framework and its core concepts.(10 minutes )
Def make sure to go over https://p5js.org/examples/ :)

2023-06-29 16:23 UTC, linkai101 commented on Visual Experiences with p5.js.md
> +2. **Part 1:** Understanding the p5.js framework and its core concepts.(10 minutes )
Also maybe explain how p5.js could be integrated into other HTML/CSS elements of a website (background, interactive component, etc.)

2023-06-29 16:23 UTC, linkai101 commented on Visual Experiences with p5.js.md
> +### Breakdown
Since you describe the steps pretty vaguely ("explore", "experimenting", etc.), I assume most of the jam would be hack clubbers following along while the presenter is showing various p5.js features. What are some specific examples of what they could make or how they could customize their creation throughout/at the end of the jam? (e.g. making an interactive fractal, a painting app, simulating smoke particles, etc.) -- stuff like this could be helpful to include

2023-06-30 05:08 UTC, euphorichubbbb commented on Visual Experiences with p5.js.md
> +- **Platform Limitations:** Windows, macOS, Linux, and web browsers
for what

2023-06-30 05:12 UTC, Arpan-206 commented on Visual Experiences with p5.js.md
> +- **Platform Limitations:** Windows, macOS, Linux, and web browsers
He mean that you can just put none as in it has no platform limitations

2023-06-30 06:52 UTC, Arpan-206 approved these changes
LGTM!

2023-06-30 16:57 UTC, linkai101 approved these changes
LGTM, looking forward to this jam!

2023-07-07 15:25 UTC, sarthaktexas requested changes

2023-07-07 15:25 UTC, sarthaktexas commented on Visual web art with p5.js.md
> +3. **Part 2:**  Designing smoke particles using code. Students will experiment with using ellipses or circles to represent smoke particles. They will use random functions to create a cloud-like effec
Can you talk about using different tools and creating different particles? Just because it looks like everyone will create the same thing.

2023-07-08 08:01 UTC, euphorichubbbb commented on Visual web art with p5.js.md
> +3. **Part 2:**  Designing smoke particles using code. Students will experiment with using ellipses or circles to represent smoke particles. They will use random functions to create a cloud-like effec
@sarthaktexas made the changes

2023-07-10 15:38 UTC, sarthaktexas commented
hey! after discussing this internally, we've decided that the quality of this jam is not up to par with the other jams we have merged and therefore, we will not be accepting it. thank you for the submission!

2023-07-10 15:38 UTC, closed without merging