WebGL Shaders: Drawing fractals with JavaScript
hackclub/jams-bounty pull request #23
Opened 2023-06-28 05:32 UTC by NalinPlad

Thanks for making a PR! Please fill in the below:

Name: Ajith

Do you run a club? Not a hack club at my school, only a robotics club

What relevant experiences do you have to help you write this Jam? A wrote [a version of this project](https://github.com/NalinPlad/gpu_fractals) using webgpu earlier this year. I also researched this topic and webgl / webgpu for long time outside of the project as well

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam? Yes

2023-06-28 06:22 UTC, Arpan-206 commented
This PR is missing a lot of the questions that haven't been answered.

2023-06-28 14:48 UTC, jianmin-chen commented
I think this is so so cool! (I've been wanting to learn about WebGL.) What's the timeframe for this though? Is it doable in one session?

2023-06-28 15:06 UTC, Arpan-206 commented
https://github.com/hackclub/Jams/pull/12/files

Should provide a pretty good idea of what kind of PR structure we're going for.

2023-06-28 16:29 UTC, NalinPlad commented
> I think this is so so cool! (I've been wanting to learn about WebGL.) What's the timeframe for this though? Is it doable in one session?

I think the project can definitely be completed in an hour, if I go over most of the boilerplate code quickly. When I first did the project I spent most of the time on wikipedia trying to find resources on the actual math. So with the Jam, it would be much simpler and faster due to having a simple explanation of it created by me.

2023-06-28 16:31 UTC, NalinPlad commented
> https://github.com/hackclub/Jams/pull/12/files
> 
> Should provide a pretty good idea of what kind of PR structure we're going for.

I updated the file, let me know if there are any other questions that you have for the Jam

2023-06-29 09:46 UTC, Arpan-206 commented
> > https://github.com/hackclub/Jams/pull/12/files
> > Should provide a pretty good idea of what kind of PR structure we're going for.
> 
> I updated the file, let me know if there are any other questions that you have for the Jam

Are you sure you pushed the changes?

2023-06-29 15:39 UTC, sarthaktexas approved these changes
I'm with JC, there's some time considerations that I'm concerned about but I trust your judgement.

2023-06-29 15:43 UTC, sarthaktexas requested changes
I seem to have missed the breakdown part, as well as some of the questions. Can you please add those?

2023-06-29 17:22 UTC, NalinPlad commented
The Overview section was the breakdown, so I renamed it to that, and I added a rough meeting outline

2023-06-30 05:56 UTC, Arpan-206 requested changes
Minor changes

2023-06-30 05:56 UTC, Arpan-206 commented on jams/fractals.md
> +### Breakdown
Would you mind adding time estimates for each step?

2023-06-30 16:42 UTC, NalinPlad commented
Updates with time estimates and consolidated some of the steps

2023-06-30 16:48 UTC, Arpan-206 approved these changes
LGTM!

2023-07-03 22:00 UTC, NalinPlad commented
@sarthaktexas any updates or any more questions?

2023-07-05 18:40 UTC, linkai101 approved these changes
LGTM too! Love how it makes a math concept actually fun to learn, and I can def see the appeal. I'm not familiar with WebGL but I look forward to seeing this jam!

2023-07-05 20:54 UTC, sarthaktexas approved these changes

2023-07-05 20:59 UTC, NalinPlad commented
Thanks to all the reviewers! I look forward to working on this

2023-07-06 01:06 UTC, merged

2023-07-10 06:32 UTC, faisalsayed10 commented
Hi @NalinPlad, could you please provide me your slack username?

2023-07-10 14:32 UTC, NalinPlad commented
> Hi @NalinPlad, could you please provide me your slack username?

@notmysql on slack