Multi-part jam proposal for Unity whack-a-mole game
hackclub/jams-bounty pull request #24
Opened 2023-06-29 15:09 UTC by grymmy

Thanks for making a PR! Please fill in the below:

Name:
Graham Darcey

Do you run a club?
No

What relevant experiences do you have to help you write this Jam? 
I have a significant amount of experience as a Unity developer.

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam?
Yes

2023-06-29 15:16 UTC, grymmy commented
I did a quick implementation pass of this yesterday, still rough but is probably like 80% complete.  Here's a vid of what it looks like (the TLDR game concept is you will be rewarded more when saving the critters right before they're smushed).

https://github.com/hackclub/Jams/assets/43505167/90ab75ca-a95f-4470-a105-8a810e82ccfc

2023-06-29 15:44 UTC, sarthaktexas reviewed
This is really cool

2023-06-29 15:44 UTC, sarthaktexas commented on jams/close_call.md
> +_Time estimation:_ 5 Hours
jesus christ

2023-06-29 15:44 UTC, sarthaktexas commented on jams/close_call.md
> +  - Readers will be prompted to use their own different assets for their game
Can you provide links/information where they can design it as well as what they need to design?

2023-06-29 15:44 UTC, sarthaktexas commented on jams/close_call.md
> +- Jam 2: Prefab creation, script setup, spawning cute critters (and dropping anvils on them)
Is there an opportunity to drop something else? :)

2023-06-29 16:06 UTC, linkai101 requested changes
Love this jam. I first learned Unity with these types of multi-part tutorials and I could see hack clubbers loving this.

2023-06-29 16:06 UTC, linkai101 commented on jams/close_call.md
> +### Breakdown
Can you specify time estimations for each part? I assume it'd be an hour each

2023-06-29 16:06 UTC, linkai101 commented on jams/close_call.md
> +_Customization opportunity:_ There will be several prompted opportunities for people following the jam to modify the game logic & aesthetics to make the game "theirs".  There will also be some sugges
Definitely a lot of potential for visual customization! What are some specific examples for game logic and feature customization?

2023-06-29 16:06 UTC, linkai101 commented on jams/close_call.md
> +- Jam 3: Adding game logic, UI, and click handling
not sure if you had this in mind for UI already but maybe have an optional part for creating a main menu/pause menu!

2023-06-29 16:10 UTC, Arpan-206 commented
This looks very, very cool, only thing I'm a little concerned about is the customisability, I mean, I get how you can create your own game but want to see how it will still follow a structure and still be very customisable

2023-06-29 18:53 UTC, grymmy commented on jams/close_call.md
> +  - Readers will be prompted to use their own different assets for their game
I will encourage readers to potentially source free models from the Unity Asset Store probably (might also mention some other sites where people can acquire models w/ reasonable licenses).  Designing would be done within the editor itself.  Describing it more at this point would kinda be authoring the actual content itself...

2023-06-29 18:54 UTC, grymmy commented on jams/close_call.md
> +- Jam 2: Prefab creation, script setup, spawning cute critters (and dropping anvils on them)
Both that, and also changing the models/behaviors of the things getting smushed, yes.

2023-06-29 18:55 UTC, grymmy commented on jams/close_call.md
> +### Breakdown
Yes, 1 hour each, 5 total.

2023-06-29 19:10 UTC, grymmy commented on jams/close_call.md
> +_Customization opportunity:_ There will be several prompted opportunities for people following the jam to modify the game logic & aesthetics to make the game "theirs".  There will also be some sugges
Modifying the scoring rules, gravity settings, customizing the splatter effect, changing the models / props placed in the environment, lighting of the environment, camera positioning / post-processing, UI placement & design, spawning cadence of objects.  Many of these things would require custom code/script changes as well as settings changes within the editor to accomplish.  I would prefer not to nail myself down **too** much on exactly what suggestions would be made before authoring the actual content, but hopefully the items I listed show there's plenty of fruit on the tree re: customization both of visuals and underlying logic/code.

While many things will be suggested, at its core it will of course still be a guide to implementing a whack-a-mole-ish game.

2023-06-29 19:12 UTC, grymmy commented on jams/close_call.md
> +- Jam 3: Adding game logic, UI, and click handling
There is a main menu - I might leave pause to be implemented by the reader actually, that's a pretty good straight-forward one...

2023-06-29 19:13 UTC, grymmy commented
> This looks very, very cool, only thing I'm a little concerned about is the customisability, I mean, I get how you can create your own game but want to see how it will still follow a structure and still be very customizable, i.e, everyone ends up with a different product
I hope my specific examples in the commentary above show there ample amount of customizability ideas across multiple dimensions.

2023-06-29 19:17 UTC, grymmy commented on jams/close_call.md
> +_Time estimation:_ 5 Hours
Do you have a little extra color to add here?  🤣. For clarity though, this would be a series of 5 1-hour jams.

2023-06-30 00:54 UTC, Arpan-206 approved these changes
Looks fantastic to me!

2023-06-30 17:03 UTC, linkai101 commented on jams/close_call.md
> +_Customization opportunity:_ There will be several prompted opportunities for people following the jam to modify the game logic & aesthetics to make the game "theirs".  There will also be some sugges
ah yup makes sense!

2023-06-30 17:05 UTC, linkai101 approved these changes
looks good!

2023-06-30 17:05 UTC, linkai101 approved these changes
looks good!

2023-07-03 15:29 UTC, merged