3D Modeling Workshop Proposal
hackclub/jams-bounty pull request #26
Opened 2023-06-30 02:27 UTC by thesuperRL

Thanks for making a PR! Please fill in the below:

Name:

Do you run a club? 

What relevant experiences do you have to help you write this Jam?

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam?

2023-06-30 02:28 UTC, thesuperRL commented
Name: Ryan Li

Do you run a club? Yes

What relevant experiences do you have to help you write this Jam? I have 3D modeled for 2 years, and I have even started a company selling products I model and then 3D print or Laser Cut.

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam? Yes

2023-06-30 02:51 UTC, Arpan-206 commented
Sorry, but I'm afraid we're only looking for Web based jams for the bounty.

(But, I would love to see this as a Jam since I'm looking forward to learning 3D modelling, hehe)

2023-06-30 05:09 UTC, SerenityUX commented
This is such an awesome Jam! Is there anyway you could use software like Spline?

2023-06-30 05:09 UTC, SerenityUX commented
I love Blender and definitely think at some point we should have a Blender Jam (it's just atm we're optimizing for Clubs and many Clubs only have access to Chromebooks)

2023-06-30 05:11 UTC, Arpan-206 commented
> I love Blender and definitely think at some point we should have a Blender Jam (it's just atm we're optimizing for Clubs and many Clubs only have access to Chromebooks)

+1 on this

2023-06-30 18:12 UTC, sahitid commented on jams/3D_Modeling_Workshop.md
> +_Outcome:_ Learn to 3D Model first with TinkerCAD, then Blender, and finally, AutoDesk Fusion 360
hi! i love this idea and how you're really excited about it! however, at the moment, i feel like this is not a jam. is there any way you could incorporate this concept of 3d modeling into a project that could be done in a group/club setting?

2023-07-01 03:59 UTC, thesuperRL commented on jams/3D_Modeling_Workshop.md
> +_Outcome:_ Learn to 3D Model first with TinkerCAD, then Blender, and finally, AutoDesk Fusion 360
I can make it about maybe building a logo to be printed, or making 3D models of various objects around the school in different pieces to be joined together. 

Also, TinkerCAD has the ability to model breadboards, which can be used for electrical engineering as well.

2023-07-01 04:00 UTC, thesuperRL commented
> Sorry, but I'm afraid we're only looking for Web based jams for the bounty.
> 
> (But, I would love to see this as a Jam since I'm looking forward to learning 3D modelling, hehe)

I just edited it, it is now web based since we use TinkerCAD instead of other programs.

2023-07-01 12:56 UTC, Arpan-206 commented on jams/3D_Modeling_Workshop.md
> +_Outcome:_ Learn to 3D Model first with TinkerCAD, then Blender, and finally, AutoDesk Fusion 360
This was one of my concerns too.

2023-07-03 16:09 UTC, SerenityUX commented
wowowwowoowow!!! :D 

(so excited for the rest of the team to check this out)

2023-07-03 19:28 UTC, sahitid commented on jams/3D_Modeling_Workshop.md
> +_Outcome:_ Learn to 3D Model first with TinkerCAD, then Blender, and finally, AutoDesk Fusion 360
I like those ideas! I'm glad you went back and edited your Jams to change the outcome/goal.

2023-07-04 15:58 UTC, Arpan-206 commented
Can you delete the extra file like the one that's not web based?

2023-07-04 17:38 UTC, thesuperRL commented
> Can you delete the extra file like the one that's not web based?

I just did

2023-07-04 17:45 UTC, Arpan-206 requested changes
Answers need to be a little more verbose.

2023-07-04 17:45 UTC, Arpan-206 commented on jams/3D_Modeling_Web_Based.md
> +**Make sure your proposal (similar to the one above) answer these questions about your Jam idea:**
The answers to the questions below are a little short and vague, find expanding on them a little bit?

2023-07-04 17:45 UTC, Arpan-206 commented on jams/3D_Modeling_Web_Based.md
> +### Breakdown
Can you add time estimates for each of the steps?

2023-07-05 02:37 UTC, thesuperRL commented on jams/3D_Modeling_Web_Based.md
> +### Breakdown
I've been told I model pretty quickly, so I'm going to give pretty generous estimates

2023-07-05 02:37 UTC, thesuperRL commented on jams/3D_Modeling_Web_Based.md
> +**Make sure your proposal (similar to the one above) answer these questions about your Jam idea:**
I don't see how they are vague. I'll expand best I can. Mind pointing me the vague portions so I can elaborate?

2023-07-05 11:41 UTC, Arpan-206 requested changes

2023-07-05 11:41 UTC, Arpan-206 commented on jams/3D_Modeling_Web_Based.md
> +### Breakdown
Uhh, I just wanted you to add time required for each step like
- Part 0: Learn to view items like a 3D modeler in basic shapes (10mins)

etc

2023-07-05 14:27 UTC, thesuperRL commented
@Arpan-206 I did, check the newest version

2023-07-05 16:01 UTC, Arpan-206 commented on jams/3D_Modeling_Web_Based.md
> +### Breakdown
Sorry missed it

2023-07-05 16:01 UTC, Arpan-206 approved these changes
LGTM!

2023-07-06 17:48 UTC, sarthaktexas approved these changes
Lgtm

2023-07-10 14:50 UTC, merged