Snow Globe!
hackclub/jams-bounty pull request #28
Opened 2023-06-30 16:08 UTC by VelocityDesign

Thanks for making a PR! Please fill in the below:

**Name:**
Judah Brown

**Do you run a club?** 
Yes, Tulsa Hack Club

**What relevant experiences do you have to help you write this Jam?**
I've been doing web development for a while. Additionally, I have done some minimal work with ParticlesJS to know enough about how it works and some of the more advanced features that it has.

**Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam?**
Of Course!

2023-06-30 16:10 UTC, faisalsayed10 requested changes
Could you please answer the questions that are there regarding jams in your md file?

example:
<img width="896" alt="image" src="https://github.com/hackclub/Jams/assets/36627266/fcc8bdab-f86c-412c-ad32-6bc91cd9116b">

2023-06-30 16:11 UTC, VelocityDesign commented
@faisalsayed10 I answered them in the paragraph above. Was I supposed to just answer them within that list?

2023-06-30 16:12 UTC, VelocityDesign commented
>  This jam is meant to give clubbers and newbies alike the chance to create something unique to them, while still preserving the "wow factor." The project is simple enough to follow along with, but open-ended enough to allow participants to create something akin to their knowledge level. Also, snow globes ❄️ are just fun! Participants will walk away with their own snow globe online! Club leaders can build along with the presentation and use their snow globe as an example. Personally, I want to build this jam to run as a program at my library to attract people to Tulsa Hack Club! I can't wait to see all the things people make!

2023-06-30 16:13 UTC, faisalsayed10 commented
Yeah I think it'd be better that way

2023-06-30 16:25 UTC, VelocityDesign commented
Okay, got those added!

2023-06-30 16:48 UTC, faisalsayed10 approved these changes
LGTM

2023-06-30 16:54 UTC, VelocityDesign commented
Yay!

2023-06-30 17:19 UTC, linkai101 approved these changes
ok i like it picasso

an optional addon could be adding sounds when you shake or move the globe 😁 

also just making sure, for devices without gyro capabilities, there's still touch controls right? id imagine it wouldn't be too big of an issue 👍

2023-06-30 17:20 UTC, VelocityDesign commented
> ok i like it picasso
> 
> an optional addon could be adding sounds when you shake or move the globe 😁
> 
> also just making sure, for devices without gyro capabilities, there's still touch controls right? id imagine it wouldn't be too big of an issue +1

Of course!

2023-06-30 18:31 UTC, sahitid reviewed
i personally love this jams! very excited for it

2023-06-30 18:31 UTC, sahitid commented on jams/Snowglobe.md
> +_Platform Limitations:_ There is no platform limitation for the coding part of the project. However, due to an API limitation, the motion reaction is only available on devices with a gyroscope runnin
is there an option to create the end project even without the gyroscope feature?

2023-06-30 21:19 UTC, VelocityDesign commented on jams/Snowglobe.md
> +_Platform Limitations:_ There is no platform limitation for the coding part of the project. However, due to an API limitation, the motion reaction is only available on devices with a gyroscope runnin
Yes. You can interact with the snow globe using touch. The gyroscope is only needed for the motion reaction feature.

2023-07-01 12:54 UTC, Arpan-206 approved these changes
LGTM!

2023-07-01 21:12 UTC, sarthaktexas requested changes
Overall love this, just add the things I commented and it's ready to be merged!

2023-07-01 21:12 UTC, sarthaktexas commented on jams/Snowglobe.md
> +_Customization opportunity:_ Change up the way your snow globe looks, what's precipitating, or even how the particles interact!
can you add something for changing the actual particle? maybe it's not snow but like people? or sharks? etc. thanks!

2023-07-01 21:12 UTC, sarthaktexas commented on jams/Snowglobe.md
> +_Platform Limitations:_ There is no platform limitation for the coding part of the project. However, due to an API limitation, the motion reaction is only available on devices with a gyroscope runnin
can you write this part into your proposal?

2023-07-01 21:23 UTC, VelocityDesign commented on jams/Snowglobe.md
> +_Customization opportunity:_ Change up the way your snow globe looks, what's precipitating, or even how the particles interact!
Hey! That's what I meant when I said "change what's precipitating." Thanks!

2023-07-01 21:24 UTC, VelocityDesign commented on jams/Snowglobe.md
> +_Platform Limitations:_ There is no platform limitation for the coding part of the project. However, due to an API limitation, the motion reaction is only available on devices with a gyroscope runnin
Sorry, I'm a bit confused by this comment.

2023-07-03 18:40 UTC, sarthaktexas commented on jams/Snowglobe.md
> +_Platform Limitations:_ There is no platform limitation for the coding part of the project. However, due to an API limitation, the motion reaction is only available on devices with a gyroscope runnin
it’s that you can do two different things but I think you did that, so resolve this if you agree

2023-07-03 20:40 UTC, SerenityUX commented
WAHOOOO THIS IS AWESOME!

2023-07-10 17:23 UTC, merged