Codeless GDevelop Game Jam
hackclub/jams-bounty pull request #29
Opened 2023-06-30 16:13 UTC by edmundlzen

Thanks for making a PR! Please fill in the below:

Name: Edmund

Do you run a club?: No.

What relevant experiences do you have to help you write this Jam?: Made a game using GDevelop before, decent coding experience.

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam?: Yes.

2023-06-30 16:14 UTC, edmundlzen commented
No idea if a codeless game jam would fly, but I felt like it would lower the barrier of entry of making a game for a lot of people!

2023-07-01 12:53 UTC, Arpan-206 requested changes
Answers to the Q/A are a little vague and short, time estimates for each step.

2023-07-01 12:53 UTC, Arpan-206 commented on jams/codeless-gd-game-jam.md
> +A: A showcase session at the end, letting people demo their own versions of the game.
I am not sure if I'm satisfied with this answer, can't point out why but a look at the closed PRs may be helpful.

2023-07-01 12:53 UTC, Arpan-206 commented on jams/codeless-gd-game-jam.md
> +A: Making their own game!
Can you expand this a bit?

2023-07-01 12:53 UTC, Arpan-206 commented on jams/codeless-gd-game-jam.md
> +# Q & A
More verbose answers for this section will be very helpful.

2023-07-01 12:53 UTC, Arpan-206 commented on jams/codeless-gd-game-jam.md
> +_Time estimation:_ 1-2 hours
That's a pretty big range, it should be around 10 minutes max, like 50-60 mins or something.

2023-07-01 12:53 UTC, Arpan-206 commented on jams/codeless-gd-game-jam.md
> +### Breakdown
Mind adding time estimates for each step?

2023-07-01 13:21 UTC, edmundlzen commented on jams/codeless-gd-game-jam.md
> +### Breakdown
Done

2023-07-01 13:22 UTC, edmundlzen commented on jams/codeless-gd-game-jam.md
> +_Time estimation:_ 1-2 hours
Changed the time estimation to be more logical

2023-07-01 13:26 UTC, edmundlzen commented on jams/codeless-gd-game-jam.md
> +A: A showcase session at the end, letting people demo their own versions of the game.
Hmm 🤔 For this question specifically, a showcase session at the end seems to be about the only method possible for this kind of thing?

2023-07-01 13:26 UTC, edmundlzen commented on jams/codeless-gd-game-jam.md
> +A: Making their own game!
Done

2023-07-01 13:26 UTC, edmundlzen commented on jams/codeless-gd-game-jam.md
> +# Q & A
Made the answers for some sections more verbose

2023-07-01 13:30 UTC, Arpan-206 commented on jams/codeless-gd-game-jam.md
> +# Q & A
I was talking about answers to all the Q/A questions, they all can do with a little more explanation.

2023-07-01 13:31 UTC, Arpan-206 commented on jams/codeless-gd-game-jam.md
> +A: A showcase session at the end, letting people demo their own versions of the game.
@sarthaktexas what do you think?

2023-07-01 13:41 UTC, edmundlzen commented on jams/codeless-gd-game-jam.md
> +# Q & A
Done, added some more details to the answer as best as I could.

2023-07-03 20:39 UTC, SerenityUX commented
This is awesome!!! What do you think Hack Clubbers would learn through making a game with this no-code tool? I love that you're pushing the bounds of what we initially imagined a Jam looking like.

2023-07-04 02:11 UTC, edmundlzen commented
@SerenityUX Thanks! I think Hack Clubbers would learn more about the logic behind games without diving into code first and lets them learn how to solve problems , it's sort of like what scratch teaches kids, but more advanced.

2023-07-10 18:44 UTC, sarthaktexas commented
howdy @edmundlzen ! we thank you for your proposal, but it looks like it doesn't fit the standard we're looking for in our jams. i'm sorry to say, because of that, we can't accept your jam proposal.

2023-07-10 18:44 UTC, closed without merging