Create IMAGE CLASSIFICATION - MACHINE LEARNING
hackclub/jams-bounty pull request #30
Opened 2023-06-30 17:05 UTC by naseeb0

Object/Poses Classification of User's Choice using JS and Teachable Machine

Thanks for making a PR! Please fill in the below:

Name:

Do you run a club? 

What relevant experiences do you have to help you write this Jam?

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam?

2023-07-01 21:06 UTC, miguelaenlle commented on jams/IMAGE CLASSIFICATION - MACHINE LEARNING
> +_Time estimation_: 1 Hour
Add time estimates for each step. ex) Setup (5 minutes)

2023-07-01 21:11 UTC, miguelaenlle requested changes
Provide more detailed instructions for workshop hosts and time estimates for each segment of the workshop

2023-07-01 21:11 UTC, miguelaenlle commented on jams/IMAGE CLASSIFICATION - MACHINE LEARNING
> +_Time estimation_: 1 Hour
Add time estimates for each step, ex. "Setup (5 minutes): ..."

2023-07-01 21:11 UTC, miguelaenlle commented on jams/IMAGE CLASSIFICATION - MACHINE LEARNING
> +- Part 3: Integrate Into Your Web Page: Export your trained model into p5js editor online
Provide more instructions for the workshop host on how to incorporate the trained model into a website.

2023-07-01 21:11 UTC, miguelaenlle commented on jams/IMAGE CLASSIFICATION - MACHINE LEARNING
> +_Languages used:_ JavaScript
Mention that it uses HTML and CSS too for web integration

2023-07-01 21:11 UTC, miguelaenlle commented on jams/IMAGE CLASSIFICATION - MACHINE LEARNING
> +- Congratulations! You now possess a remarkable image classification model running smoothly in your browser, tailored to your specific object of interest.
Would add a segment at the end encouraging club members to train their own models

2023-07-02 18:35 UTC, naseeb0 commented
I have made the required changes. Can you please look into it.

2023-07-02 18:38 UTC, miguelaenlle approved these changes

2023-07-02 18:39 UTC, miguelaenlle commented
I checked out the changes, and they look good. Thank you Naseeb!

2023-07-03 20:47 UTC, SerenityUX commented
Hey naseeb0, I love this! We're already using Teachable Machine for a couple workshops. How would you feel about making this with TensorFlow & making it an intermediate/expert difficulty (one step up from just a Teachable Machine Model).

Maybe even incorporate some web scraping? 

https://www.tensorflow.org
https://scrapy.org
https://pypi.org/project/beautifulsoup4/

2023-07-04 02:59 UTC, naseeb0 commented
I think thats great! but I just wanted to create something that can be accomplished in one hour and give jammers a boost to start learning ML without installing anything anything. 
Maybe we can add addition to this learning or make Part 2 of the Workshop later on?

2023-07-04 16:00 UTC, Arpan-206 commented
Problem is, it will be counterproductive to have 2 Jams on Teachable Machine.

2023-07-05 17:35 UTC, naseeb0 commented
So then I will try to submit new workshop asap

2023-07-05 17:44 UTC, Arpan-206 commented
Sure, looking forward to it!

2023-07-05 17:44 UTC, closed without merging