Creating a Song with Tone.js
hackclub/jams-bounty pull request #32
Opened 2023-07-01 20:57 UTC by nerap08

Thanks for making a PR! Please fill in the below:

Name: Paul Trusov

Do you run a club? Yes, I run the Hack Club at the Montgomery Blair High School

What relevant experiences do you have to help you write this Jam? I have been using javascript in different projects for a few years now, I also worked on a project using Tone.js

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam? Certainly, I would be happy to help out other Hack Clubbers.

2023-07-02 03:44 UTC, Arpan-206 commented
The file is JS, can you change that to md?

2023-07-02 14:24 UTC, nerap08 commented
My bad I didn't notice it was in JS, I fixed it now.

2023-07-02 14:30 UTC, Arpan-206 requested changes
Missing answeres

2023-07-02 14:30 UTC, Arpan-206 commented on jams/Creating a Song with Tone.js.md
> +General outline:
Can you add specific timelines for each?

2023-07-02 14:30 UTC, Arpan-206 commented on jams/Creating a Song with Tone.js.md
> +7. Sharing the created songs within the Jam session.
A lot of the questions later haven't been answered.

2023-07-02 15:44 UTC, nerap08 commented
I added a timeline, but I can't seem to find the questions which I haven't answered yet.

2023-07-02 15:59 UTC, Arpan-206 commented
> I added a timeline, but I can't seem to find the questions which I haven't answered yet.

I suggest having a look at some merged PRs.

2023-07-02 16:37 UTC, nerap08 commented
I changed my file into the structure of the "Add Kaboom" jam file.

2023-07-02 16:56 UTC, miguelaenlle commented on jams/Creating a Song with Tone.js.md
> +Any device with access to replicate.
Typo: Replicate should be "Replit"

2023-07-02 17:02 UTC, miguelaenlle requested changes

2023-07-02 17:02 UTC, miguelaenlle commented on jams/Creating a Song with Tone.js.md
> +Any device with access to replicate.
Typo: Change "replicate" to "replit"

2023-07-02 17:03 UTC, miguelaenlle requested changes

2023-07-02 17:03 UTC, miguelaenlle commented on jams/Creating a Song with Tone.js.md
> +3. 5 minutes: Understanding the basics of music synthesis, including instruments, oscillators, and filters.
Go into more detail on the basics of music synthesis, and how they all connect to enable you to produce a song

2023-07-02 19:37 UTC, nerap08 commented
I have made those two changes to the file, do they look good?

2023-07-02 19:39 UTC, miguelaenlle commented
Yup, looks good @nerap08

2023-07-02 19:39 UTC, miguelaenlle approved these changes

2023-07-03 01:31 UTC, linkai101 requested changes
I love projects that involve music and code, but this seems a bit too simple for a jam imo, more like a tutorial for Tone.js rather than a jam.

So far, it's a lot like [muse](https://workshops.hackclub.com/muse/), which—don't get me wrong—is a great workshop, but given the standards for a jam, I'd recommend adding on to this idea with a specific project in mind, like a [synth pad](https://workshops.hackclub.com/synth/) or a [piano](https://workshops.hackclub.com/tunes/). (both already existing workshops) Also, there doesn't seem to be a visual component, so having that could help.  Hope that makes sense!

2023-07-03 02:57 UTC, nerap08 commented
Hey Linkai, to make the Jam more complex we can let the members make a melody and then have them code it so that the speed of the rhythm and level of the pitch can be changed by the users when running it. This would still allow the members to have the freedom to make their own song but it would also allow them to hear different variations of it each time they run it. Additionally, to add a visual component we can change the color of the background each time a new note is played. This would make it look prettier and it would allow members to see the pace of their song.

2023-07-03 15:35 UTC, Arpan-206 approved these changes
LGTM!

2023-07-03 16:58 UTC, SerenityUX commented
Great feedback Linkai!

> I love projects that involve music and code, but this seems a bit too simple for a jam imo, more like a tutorial for Tone.js rather than a jam.
> 
> So far, it's a lot like [muse](https://workshops.hackclub.com/muse/), which—don't get me wrong—is a great workshop, but given the standards for a jam, I'd recommend adding on to this idea with a specific project in mind, like a [synth pad](https://workshops.hackclub.com/synth/) or a [piano](https://workshops.hackclub.com/tunes/). (both already existing workshops) Also, there doesn't seem to be a visual component, so having that could help. Hope that makes sense!

I think with some work, this can be made into a SUPER FUN JAM that I would love to use with my club!

How might Hack Clubbers be able work together to make a really awesome symphony?

2023-07-03 22:18 UTC, nerap08 commented
With the ability to control tempo without much work, clubs can effortlessly combine different melodies, into harmony. This ability would enable groups to join their projects together, making an awesome symphony.

2023-07-05 18:10 UTC, linkai101 commented
Yeah creativity and uniqueness definitely isn't an issue here. You know, this kinda reminds me of Google's [blob opera](https://artsandculture.google.com/experiment/blob-opera/AAHWrq360NcGbw?hl=en). Making that with Tone.js would be awesome--and the color changing def helps.

2023-07-05 18:13 UTC, linkai101 approved these changes
This looks good to me! Though I agree with Thomas that it may need some work, that can be addressed in the next phase and I definitely look forward to this jam. :)

2023-07-06 17:55 UTC, sahitid requested changes
hi! love the idea, but this very closely mimics existing workshops on the hack club workshops page (such as synth and piano). we're really looking for something new with these bounty proposals and i'm afraid this is not meeting the mark.

2023-07-06 17:56 UTC, closed without merging