Create_Build_Your_Own_Adventure.md
hackclub/jams-bounty pull request #39
Opened 2023-07-08 02:36 UTC by necode2

Thanks for making a PR! Please fill in the below:

Name: Noor Elbanna

Do you run a club? 
Yes! I run a coding club at my school with three other leaders!

What relevant experiences do you have to help you write this Jam?
I've been programming since the 2nd grade and now as a sophomore in high school building adventures games have been one of my favorites! I've been programming in several languages, mainly Python, however I have experience with Java, HTML and CSS. This Jam would also provide me with the opportunity of combining things I have learned over the years into one package. 

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam?
Yes! I will be active and even try to provide fun challenges alongside the project.

2023-07-10 15:24 UTC, cytronicoder requested changes
Can you answer the questions found at the bottom of the [example file?](https://github.com/hackclub/jams/blob/main/jams/example.md)

2023-07-10 15:24 UTC, cytronicoder commented on jams/Build_Your_Own_Adventure.md
> +### Part 1: (ETC: Simplest and can be completed in under 30 minutes)
This part should be setting up the Replit project and installing relevant dependencies if needed

2023-07-10 15:24 UTC, cytronicoder commented on jams/Build_Your_Own_Adventure.md
> +### Part 2: (ETC: Increased in difficulty and can take up to 1 hour)
As per my comment above, you should shift all these sections down - additionally, I think. that part 1 and 2 should be the sections with the most details, while allowing clubs themselves to explore how they want to take this

2023-07-10 16:59 UTC, linkai101 requested changes
Great idea! I loved making text adventure games when I started learning to code.

Just a few thoughts:
1) I assume the 3 parts are supposed to be done in separate meetings, which might not be the most appealing to most club members. IMO the project would be dragged on for too long to be held for 3 club meetings, especially one meeting just for adding music.

2) The breakdown, especially for part 1, is super vague. Could you add more specific steps and time durations? (e.g. overview of user input and if/else statements, etc.) Mainly steps for actually implementing the game with code.

2023-07-10 17:25 UTC, sarthaktexas commented
I would love to merge this, can you finish the changes request above @necode2 ?

2023-07-11 04:07 UTC, necode2 commented
Thank you so much for all the feedback! I'll implement this and have a new version ready tomorrow! Also, would it be possible to get a quick snapshot of the questions from the example file? I am unable to open it from my end.

2023-07-11 13:37 UTC, sahitid commented
love it! lgtm

2023-07-11 13:37 UTC, merged