Create AI powered Trip Itinerary
hackclub/jams-bounty pull request #4
Opened 2023-06-23 20:20 UTC by ShubhamPatilsd

Name: Shubham Patil

1. Do you run a club? 
    - Yes, the Mission San Jose High School CS Club
2. What relevant experiences do you have to help you write this Jam?
     - Creating https://tripley.app, and this exact feature is what we have in our trip calendar
3. Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam?
    - Yes

2023-06-23 21:33 UTC, SerenityUX commented
Thanks for being the first Jam submission. You helped us realize some issues with our template (which we've revised).

I love this idea (especially because you have experience building in this niche).

How might we ensure that every outcome of this Jam is significantly different both visually and technically? How can we ensure a low floor and a high ceiling?

2023-06-26 23:47 UTC, ShubhamPatilsd commented
The jam will be the same up until you want to add more features (e.g. what kinds of parameters you want to feed in, how you display the results). A future option could be having a map view of all the places laid out, with photos for each location in your itinerary.

We can lower the floor by ONLY inputting the location instead of the dates + the location, so that people who make this can add dates as a factor (e.g. looking at fall colors during October). As I mentioned above, the way that someone could style with CSS is endless and the way they present the data from ChatGPT is also another way that they can have creative freedom!

2023-06-29 16:23 UTC, Arpan-206 reviewed
Minor change but looks good otherwise!

2023-06-29 16:23 UTC, Arpan-206 commented on jams/itinerary.md
> +### Breakdown
Would you mind providing time estimates for each step?

2023-06-30 14:18 UTC, faisalsayed10 requested changes
Have one question, other than that lgtm

2023-06-30 14:18 UTC, faisalsayed10 commented on jams/itinerary.md
> +    - Changing the scope from a global thing to just in a city (i.e. only in San Francisco)
are these customizations just in terms of tweaking the gpt prompt or is there something actually different in terms of technicality? imo technical customizations would be preferable here.

2023-07-05 08:40 UTC, ShubhamPatilsd commented on jams/itinerary.md
> +    - Changing the scope from a global thing to just in a city (i.e. only in San Francisco)
they always can be technical customizations. for example instead of typing in your destination, you could have a map where you choose your destination.

2023-07-08 06:30 UTC, faisalsayed10 approved these changes
looks good to me

2023-07-10 17:27 UTC, sahitid commented
i love this idea! lgtm

2023-07-10 17:28 UTC, merged