Create npx-portfolio.md
hackclub/jams-bounty pull request #40
Opened 2023-07-08 03:28 UTC by aboutdavid

Thanks for making a PR! Please fill in the below:

Name: David (aboutdavid)

Do you run a club? Yes!

What relevant experiences do you have to help you write this Jam? I've made a similar portfolio before (`npx davidfolio`, i think)

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam? Yes

2023-07-10 14:34 UTC, zeyuyaoy requested changes
This looks super cool! I wanted to do something like this a while ago :)

Could you
1. answer the questions at the bottom from [the example file](https://github.com/hackclub/jams/blob/main/jams/example.md) and
2. include that Replit can be used to build this project, and add steps for those who are using Replit to set up this project?

2023-07-10 17:17 UTC, sarthaktexas requested changes
I would approve this as I'm very excited but you are missing the questions at the bottom. Please add them so this can be merged asap!

2023-07-10 19:02 UTC, aboutdavid commented
Sure! I'll go ahead and add those things

2023-07-10 19:55 UTC, aboutdavid commented
okay i went and added the questions + added the fact it could work on repl

2023-07-11 12:53 UTC, Arpan-206 requested changes
Time estimation thingies, looks good otherwise!

2023-07-11 12:53 UTC, Arpan-206 commented on jams/npx-portfolio.md
> +### Breakdown
Can you add timestamps for each step in the breakdown?

2023-07-11 13:37 UTC, sahitid commented
sorry, although we loved this idea, we'll have to close this proposal due to the fact that you've missed the deadline.

2023-07-11 13:37 UTC, closed without merging