Tuning Your Instrument with Google Teachable Machine
hackclub/jams-bounty pull request #6
Opened 2023-06-23 22:22 UTC by ganning127

Name: Ganning Xu

Do you run a club? Yes, I just graduated from high school though. My club was at the North Carolina School of Science and Math.

What relevant experiences do you have to help you write this Jam? I made a [workshop](https://www.youtube.com/watch?v=xQjgui5Un-s&feature=youtu.be) on it before (but would love to make it much more polished here). I also have web development experience (react.js, next.js, but this JAM uses HTML/CSS/JS) and machine learning experience with natural language processing (this JAM uses Google Teachable Machine). I've also used Google Teachable Machine a LOT :)

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam? Certainly!

2023-06-27 17:30 UTC, faisalsayed10 requested changes
Overall this is a fun workshop, although there are a few things. 

One concern I have is that wouldn't this jam be restricted to people who have some kind of musical instrument with them? Curious about how people who don't have any instruments would interact with this project.

2023-06-27 17:30 UTC, faisalsayed10 commented on jams/tuning-instruments-with-google-teachable-machine.md
> +- Part 1: find audio samples on YouTube (such as [this one](https://www.youtube.com/watch?v=buimPG01gcs)) with different notes (A, B, C, D, E, F, G, sharps/flats)
would you be providing all the audio samples with the jam? cuz I think people may find it difficult to find the samples, and it'd be time consuming task.

2023-06-27 17:30 UTC, faisalsayed10 commented on jams/tuning-instruments-with-google-teachable-machine.md
> +- Part 7: give everyone next steps on how to further customize
could you please elaborate on this and add some examples?

2023-06-27 17:59 UTC, sarthaktexas requested changes

2023-06-27 17:59 UTC, sarthaktexas commented on jams/tuning-instruments-with-google-teachable-machine.md
> +_Customization opportunity:_ Everyone can train their model to be notes of different instruments (ie guitar, piano, violin, etc.). Sharps and flats can also be added. Additionally, the HTML/CSS/JS of
While this is technically customizable, it is still a tuner at the core, and this isn't really what a jam is. I think that this jam is not a jam, but a workshop.

2023-06-27 18:10 UTC, linkai101 requested changes
Love this idea!

Adding to fayd's question, for those who don't have/play instruments, I believe they could still use their voice or some voice-based instrument (kazoo, etc.) to train/test their model, which I imagine could be quite fun 😆

2023-06-27 18:10 UTC, linkai101 commented on jams/tuning-instruments-with-google-teachable-machine.md
> +- Part 2: play those audio samples on your phone in front of your computer's mic to train the Google Teachable Machine audio model to identify different notes (A, B, C, D, E, F, G, sharps/flats)
I would imagine it'd be a bit noisy (and hard to get a clean recording) if everyone was doing this at the same time in a room. Could this be an issue?

2023-06-28 13:24 UTC, ganning127 commented
Closing this PR; I'm going to focus on the Python Gradio Jam instead!

2023-06-28 13:24 UTC, closed without merging