Getting Started with Lua
hackclub/jams-bounty pull request #7
Opened 2023-06-23 23:00 UTC by LucasHT22

Thanks for making a PR! Please fill in the below:

Name: Lucas

Do you run a club? Trying

What relevant experiences do you have to help you write this Jam? Basically practice, trying some things with this language.

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam? Sure, I think the best way to learn more is teaching

2023-06-26 14:12 UTC, sarthaktexas requested changes
Overall, great start. I'd like a bit more explaining on some points because
- i am unfamiliar with Lua
- i am unsure how this would be run
- i am confused on potential applications

All of us on the review team will give you feedback as you improve this proposal :)

2023-06-26 14:12 UTC, sarthaktexas commented on jams/getting_started_with_lua.md
> +_Customization opportunity:_ you can make everthing with Lua!
I understand you can make everything with Lua, but this is a broad customization opportunity. A beginner would not know how to make everything with Lua. Maybe give at least 3 different paths they can follow to create something? They don't *have* to follow it but at least it gives them a push. One thing I know for Lua, that I would like to do, is create an NSpire App! https://education.ti.com/en/resources/lua-scripting

2023-06-26 14:12 UTC, sarthaktexas commented on jams/getting_started_with_lua.md
> +- Part 2: let's combinate functions to do something (ex.: calculator - basic, scrabble game - internediate)
this one is a bit broad, can you elaborate on this part more? how would the writing be structured, how would this be visually displayed on a presentation/website (we can use custom components ofc). I love this idea, I'm just unsure on the presentation style.

2023-06-26 14:12 UTC, sarthaktexas commented on jams/getting_started_with_lua.md
> +- Why should Hack Clubbers care about this project? Lua it's a simple language, perfect for beginners
This line is a bit too broad as well, is there any application use for Lua? I'd love to see real world examples of Lua being used and any potential use cases for Hack Clubbers specifically.

2023-06-26 14:12 UTC, sarthaktexas commented on jams/getting_started_with_lua.md
> +- General outline of a club meet doing the Jam: Do the Jam, explore possibilities with the language
We're looking for a time table, like "spend 20 minutes doing the jam" "spend the other 40 minutes playing with Lua" (this is not a good outline, but you get the gist). How long would each part take? Basically, what I want to see is a break down per part of the jam, when they will do what, so other club leaders don't spend too long on one slide.

2023-06-26 14:12 UTC, sarthaktexas commented on jams/getting_started_with_lua.md
> +- What Club Members will walk away with (both in terms of knowledge and in terms of product): basic knowledge of functions
this is great, what kind of functions? can you provide a list of things they might be able to do?

2023-06-26 14:12 UTC, sarthaktexas commented on jams/getting_started_with_lua.md
> +- What makes this workshop fun or interesting for Club Members? perfect for beginners
I understand this is a repetition of the question above, but I would like a more specific answer. Look at the comment above!

2023-06-26 14:12 UTC, sarthaktexas commented on jams/getting_started_with_lua.md
> +- How will you allow Club Leaders to add their own project to the Jam presentation (giving them a sense of ownership over the meeting)? in Part 2, we'll give some things that you can do with Lua, but
**This is great! This is exactly what I was looking for while reading.** Can you expand this on the other bullet points, and provide more examples if you can?

2023-06-26 16:25 UTC, LucasHT22 commented on jams/getting_started_with_lua.md
> +_Customization opportunity:_ you can make everthing with Lua!
Looks great an NSpire App! What about a Scrabble and Minesweeper? We can also add this list https://exercism.org/tracks/lua/exercises/ as "get more ideas"

2023-06-26 16:35 UTC, LucasHT22 commented on jams/getting_started_with_lua.md
> +- Part 2: let's combinate functions to do something (ex.: calculator - basic, scrabble game - internediate)
I think a slide making analogy to lego pieces as parts of the code would be interesting, but I don't know if it would be the best option, what do you think?

2023-06-26 16:41 UTC, LucasHT22 commented on jams/getting_started_with_lua.md
> +- Why should Hack Clubbers care about this project? Lua it's a simple language, perfect for beginners
Most of the most famous real examples are games:
Roblox games
Angry Birds
World of Warcraft

2023-06-26 16:47 UTC, LucasHT22 commented on jams/getting_started_with_lua.md
> +- General outline of a club meet doing the Jam: Do the Jam, explore possibilities with the language
I think that without the jam itself ready it's kind hard to calculate, but I think 5-10 minutes to fork the replit, 10-15 minutes to present the main keywords (in Lua there are only 21 keywords") and 30 minutes to play with the language

2023-06-26 16:55 UTC, LucasHT22 commented on jams/getting_started_with_lua.md
> +- What Club Members will walk away with (both in terms of knowledge and in terms of product): basic knowledge of functions
I got the term wrong there, it would be keywords and not functions, but the idea is to learn the 21 lua keywords that are practically used in all languages, they are: and, break, do, else, elseif, end, false, for, function, if, in, local, nil, not, or, repeat, return, then, true, until, while

2023-06-26 16:56 UTC, LucasHT22 commented on jams/getting_started_with_lua.md
> +- How will you allow Club Leaders to add their own project to the Jam presentation (giving them a sense of ownership over the meeting)? in Part 2, we'll give some things that you can do with Lua, but
Sorry, but wdym exactly with "this"?

2023-06-27 12:49 UTC, sarthaktexas commented on jams/getting_started_with_lua.md
> +- How will you allow Club Leaders to add their own project to the Jam presentation (giving them a sense of ownership over the meeting)? in Part 2, we'll give some things that you can do with Lua, but
OH that's so weird, my bad. I mean the last bullet point.

2023-06-27 12:49 UTC, sarthaktexas commented on jams/getting_started_with_lua.md
> +_Customization opportunity:_ you can make everthing with Lua!
I'm just a bit unsure about what the final product is in this jam. This seems to be more of a teaching workshop than a product jam.

2023-06-27 12:50 UTC, sarthaktexas commented on jams/getting_started_with_lua.md
> +- Part 2: let's combinate functions to do something (ex.: calculator - basic, scrabble game - internediate)
No that's not what I meant. I mean more like would there be challenges throughout? What would people be building and how would they learn that?

2023-06-27 12:50 UTC, sarthaktexas commented on jams/getting_started_with_lua.md
> +- Why should Hack Clubbers care about this project? Lua it's a simple language, perfect for beginners
Great, but are there any smaller use cases? Similar to any of the ones you and I mentioned above.

2023-06-27 12:51 UTC, sarthaktexas commented on jams/getting_started_with_lua.md
> +- General outline of a club meet doing the Jam: Do the Jam, explore possibilities with the language
Can you put these different slide names in the outline?

2023-06-27 12:51 UTC, sarthaktexas commented on jams/getting_started_with_lua.md
> +- What Club Members will walk away with (both in terms of knowledge and in terms of product): basic knowledge of functions
I understand, can you go over just a few instead of all of them? This can be a daunting thing for some people if they don't know any other languages.

2023-06-27 12:52 UTC, sarthaktexas commented
As a whole, I think that this proposal has no clear product and no clear outline either and adding that would make it more clear for us to see what people would be building and how. If you want to hop on a zoom, ping me on the Slack!

2023-06-27 16:07 UTC, LucasHT22 commented on jams/getting_started_with_lua.md
> +_Customization opportunity:_ you can make everthing with Lua!
What would you add to make it more of a jam? There aren't any ready-made jams so it's hard for me to understand what exactly would make it feel more like a jam:)

2023-06-27 16:17 UTC, LucasHT22 commented on jams/getting_started_with_lua.md
> +- Why should Hack Clubbers care about this project? Lua it's a simple language, perfect for beginners
Hangman, Tic-Tac-Toe.....

2023-06-27 16:17 UTC, LucasHT22 commented on jams/getting_started_with_lua.md
> +- General outline of a club meet doing the Jam: Do the Jam, explore possibilities with the language
sure

2023-06-27 16:23 UTC, LucasHT22 commented on jams/getting_started_with_lua.md
> +- What Club Members will walk away with (both in terms of knowledge and in terms of product): basic knowledge of functions
Sure: function, for, return, while, if

2023-06-27 16:24 UTC, LucasHT22 commented on jams/getting_started_with_lua.md
> +- How will you allow Club Leaders to add their own project to the Jam presentation (giving them a sense of ownership over the meeting)? in Part 2, we'll give some things that you can do with Lua, but
Just to make sure, as the last bullet point you mean the Roblox Studio point?

2023-06-27 16:29 UTC, LucasHT22 commented
> As a whole, I think that this proposal has no clear product and no clear outline either and adding that would make it more clear for us to see what people would be building and how. If you want to hop on a zoom, ping me on the Slack!

Sorry for not have a very clear proposal, but know that I would love to make it possible. What's your @ on Slack?

2023-06-29 15:14 UTC, sarthaktexas commented
@sarthak i believe, you should be able to find me in the #jams channel

2023-06-29 15:15 UTC, sarthaktexas requested changes

2023-06-29 15:15 UTC, sarthaktexas commented on jams/getting_started_with_lua.md
> +_Customization opportunity:_ you can make everthing with Lua!
There has to be an end product that doesn't look the same from club member to member.

2023-06-29 15:15 UTC, sarthaktexas commented on jams/getting_started_with_lua.md
> +- What Club Members will walk away with (both in terms of knowledge and in terms of product): basic knowledge of functions
Ok perfect, can you make a project with just those?

2023-06-29 15:15 UTC, sarthaktexas commented on jams/getting_started_with_lua.md
> +- How will you allow Club Leaders to add their own project to the Jam presentation (giving them a sense of ownership over the meeting)? in Part 2, we'll give some things that you can do with Lua, but
Well, generally, yes.

2023-07-01 23:25 UTC, LucasHT22 commented on jams/getting_started_with_lua.md
> +- What Club Members will walk away with (both in terms of knowledge and in terms of product): basic knowledge of functions
Yep!

2023-07-03 20:38 UTC, LucasHT22 commented
I give it up, I'm not an expert at anything, thanks for the opportunity

2023-07-03 20:38 UTC, closed without merging