Text Summarization in Python, Deploying the Model with Gradio
hackclub/jams-bounty pull request #8
Opened 2023-06-23 23:10 UTC by ganning127

**Name**: Ganning Xu

**Do you run a club?** Yes, at the North Carolina School of Science and Math (I just graduated high school though)

**What relevant experiences do you have to help you write this Jam?** The first language I learned (and my favorite language) is Python. I also did a natural language machine learning research project in Python (though this workshop requires no machine learning, and is all intuitive!)

**Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam?** Of course, happy to help :)

2023-06-26 14:17 UTC, sarthaktexas requested changes
I love this idea, just needs more room for customization. Outline is presented beautifully and I would be very excited to run this in my club as a club leader. Thanks for the proposal!

2023-06-26 14:17 UTC, sarthaktexas commented on jams/python-text-summarization-and-gradio.md
> +_Outcome:_ Create a fully functional text summarization web-application from scratch using Python and Gradio. Anyone can use the model you create using
using...?

2023-06-26 14:17 UTC, sarthaktexas commented on jams/python-text-summarization-and-gradio.md
> +# Text Summarization in Python, Deploying the Model with Gradio
Can you write a quick explanation on what Gradio is? I know you can Google it but not everyone will when they see this jam.

2023-06-26 14:17 UTC, sarthaktexas commented on jams/python-text-summarization-and-gradio.md
> +_Requirements:_ Google Colab Access (comes free with Google/Gmail account)
This is a great tool, I'm excited to see a proposal using this :)

2023-06-26 14:17 UTC, sarthaktexas commented on jams/python-text-summarization-and-gradio.md
> +- Hooray!!! Now you've got a text summarization web app!
I really, really love this as a workshop, but this doesn't provide for customization. Look at above comment.

2023-06-26 14:17 UTC, sarthaktexas commented on jams/python-text-summarization-and-gradio.md
> +_Customization opportunity:_ We'll cover one method of using Python for text summarization (which doesn't technically involve machine learning), but there are many other methods that can be used (inc
This is a great start. It seems like a better use for this jam would be using Gradio as a dashboard for machine learning opportunities. Maybe cover that as a general Python concept, and then use gradio to display data from the model? Not sure if this makes sense, you can ping me on slack if need be.

2023-06-26 17:53 UTC, ganning127 commented
Just added your requested changes from our meeting, would love some more feedback

2023-06-27 12:56 UTC, sarthaktexas approved these changes
100%, I love this jam Ganning

2023-06-27 13:47 UTC, Arpan-206 requested changes
Just a minor query, looks good otherwise!

2023-06-27 13:47 UTC, Arpan-206 commented on jams/python-text-summarization-and-gradio.md
> +- Part 4 (extension): If you want a permanent deployed link (longer than the default 72 hours), deploy your Gradio model to HuggingFace in the terminal.
How much time is this extension expected to take?

2023-06-27 13:47 UTC, Arpan-206 commented on jams/python-text-summarization-and-gradio.md
> +- Part 4 (extension): If you want a permanent deployed link (longer than the default 72 hours), deploy your Gradio model to HuggingFace in the terminal.
Would be wonderful to factor that in as well.

2023-06-27 14:21 UTC, ganning127 commented on jams/python-text-summarization-and-gradio.md
> +- Part 4 (extension): If you want a permanent deployed link (longer than the default 72 hours), deploy your Gradio model to HuggingFace in the terminal.
Great point! It should take around 10 minutes. They would need to make a huggingface account, create a new space, and just copy and paste their code from Colab into HuggingFace. Then, it's automatically running :) 

I've added a commit that adds this to the .md file

2023-06-27 14:53 UTC, Arpan-206 approved these changes
Wonderful Jam, looking forward to using this in my club!

2023-06-29 17:21 UTC, faisalsayed10 approved these changes
LOVE THIS! quite a unique jam!

2023-06-30 00:27 UTC, merged