Create link-sharing.md
hackclub/jams-bounty pull request #9
Opened 2023-06-23 23:14 UTC by InternetRamen

Thanks for making a PR! Please fill in the below:

Name: Jaden

Do you run a club? 
Yes

What relevant experiences do you have to help you write this Jam?
I have experience working with HTML, CSS, JS, and Firebase, and I've run beginner workshops at my club and at hackathons. I know from personal experience how difficult it is to engage workshop participants.

Will you be available on Slack to provide support to Hack Clubbers who run into issues while going through your Jam?
Yes

2023-06-27 13:16 UTC, sarthaktexas approved these changes
I like this idea, just have a question!

2023-06-27 13:16 UTC, sarthaktexas commented on jams/link-sharing.md
> +  - The workshop itself only provides the minimum viable product, so jammers would have full creative freedom on the purpose of the website and how it would be used. Additionally, the CSS styling wou
okay this sounds cool, will they have enough time to do this by the end of the jam/club meeting?

2023-06-27 14:00 UTC, Arpan-206 requested changes
Looks great but needs a little bit more customisability imo.

2023-06-27 14:00 UTC, Arpan-206 commented on jams/link-sharing.md
> +- How will you ensure that every outcome of the workshop varies (i.e. how will you give jammers a sense of ownership over their project)?
Even if they are writing custom CSS, that's still just styling changes and not functional ones, so could you elaborate on how each app would be functionally different at the end?

2023-06-27 14:00 UTC, Arpan-206 commented on jams/link-sharing.md
> +- How will you ensure that every outcome of the workshop varies (i.e. how will you give jammers a sense of ownership over their project)?
Also, I get the idea that it has multiple possible implementations, but I'm afraid that still doesn't answer how the end application will be different from each other at the end of a club meeting.

2023-06-27 19:24 UTC, InternetRamen commented on jams/link-sharing.md
> +  - The workshop itself only provides the minimum viable product, so jammers would have full creative freedom on the purpose of the website and how it would be used. Additionally, the CSS styling wou
hi sarthak, I think they'd be able to finish it by the end of the jam/club meeting or at least be heavily invested and motivated to finish up with the document version.
If we're worried abt time, I think switching the email/pass login to a simple copy/paste OAuth drop-in on a single HTML page would allow jammers time to customize their project. Other ways we can cut down include creating a boilerplate with the HTML preloaded, as this project is more focused on the intermediate skill level (after intro to htmlcssjs).

2023-06-27 20:05 UTC, InternetRamen commented on jams/link-sharing.md
> +- How will you ensure that every outcome of the workshop varies (i.e. how will you give jammers a sense of ownership over their project)?
I agree with your comment about the CSS. I was thinking that the jammers who like the web design aspect more would be occupied with the CSS aspect (https://www.csszengarden.com/), but I can see that doesn't really change the outcome of the project. 

Your comment on the end application being different made me realize that a "link-sharing" app is pretty restricting, so what do you think of making this jam into a general CRUD jam (i.e. Building a CRUD app with Firebase or something)? 

I think this idea would expand the functional customization opportunities a lot. The current jam could be modified to teach jammers how to create pages that can create data and load data instead of creating a post and loading posts. This would mean the jammers could build out projects similar to these ideas: a recipe app, grade management system, achievement app (record progress on achievements), community calendar, events app, AND all the other "link-sharing apps".  

I can update the file's wording. Thanks

2023-06-28 02:35 UTC, Arpan-206 commented on jams/link-sharing.md
> +- How will you ensure that every outcome of the workshop varies (i.e. how will you give jammers a sense of ownership over their project)?
That sounds like a wonderful idea, but for now at least we need Jams to have a structure (think >60% same app) so a CRUD application won't be able to provide such a structure to it and would be far too customisable imo.

2023-06-28 15:18 UTC, InternetRamen commented on jams/link-sharing.md
> +- How will you ensure that every outcome of the workshop varies (i.e. how will you give jammers a sense of ownership over their project)?
I guess instead of a CRUD application, it'd be more like having users create "posts" and seeing all "posts" (the name of the data can vary). The jam would lead them to a basic structure of a website that loads data from a database. Then, the jammer could turn that structure into something functionally different by changing the fields of the post or how it's loaded, maybe like an app to store recipes or an app that stores a list of clubs and their meeting times. The fundamental app would be the same.

Could you elaborate on what you meant by functionally different 😅?

2023-06-28 15:34 UTC, Arpan-206 commented on jams/link-sharing.md
> +- How will you ensure that every outcome of the workshop varies (i.e. how will you give jammers a sense of ownership over their project)?
This sounds like a good plan to me!

2023-06-29 17:14 UTC, faisalsayed10 approved these changes
Overall, I like this jam idea. It focuses on some really valuable topics if you want to get into web development today. Just have a question, would love to hear your thoughts.

2023-06-29 17:14 UTC, faisalsayed10 commented on jams/data-web-app.md
> +  - This project introduces the basics of user authentication and databases which are important tools in web development. User authentication and databases are the foundation of a lot of the apps we
I like this point!

2023-06-29 17:14 UTC, faisalsayed10 commented on jams/data-web-app.md
> +  - 10 min: Parts 1-3
I just want to confirm if implementing authentication is possible to get done within 10 minutes? I've had experiences where it too me 30-60 minutes to implement full-fledged authentication. would love to hear if you're doing something different

2023-06-30 02:33 UTC, InternetRamen commented on jams/data-web-app.md
> +  - 10 min: Parts 1-3
I think using Firebase Auth makes it really easy to get started so it should be possible. If we use Google OAuth, we can create a button and then add the following code from the Firebase SDK.
```js
var provider = new firebase.auth.GoogleAuthProvider();
firebase.auth()
  .signInWithPopup(provider)
```
Instead of full-fledged authentication, I think it would be a good idea to piggyback off of existing solutions for the jammers' first experiences because of simplicity and time. 

The full solution would include something like:
```html
<button onclick="signIn()">Sign in with Google</button>
<script> 
var provider = new firebase.auth.GoogleAuthProvider();
function signIn() {
firebase.auth()
  .signInWithPopup(provider)
  .then(() => window.location.href = "/")
}
</script>
```
Ideally, the jammer would have a bit of experience using javascript 👍

2023-06-30 02:41 UTC, Arpan-206 approved these changes
LGTM!

2023-06-30 08:34 UTC, faisalsayed10 approved these changes
All good

2023-07-01 21:05 UTC, sarthaktexas commented on jams/link-sharing.md
> +  - The workshop itself only provides the minimum viable product, so jammers would have full creative freedom on the purpose of the website and how it would be used. Additionally, the CSS styling wou
okay, i'll leave it up to your minion to help you decide this.

2023-07-01 21:07 UTC, sarthaktexas approved these changes
This looks amazing!

2023-07-01 21:07 UTC, merged

2023-07-02 12:44 UTC, SerenityUX commented
A link sharing app is functionally the same as a photo sharing app or an audio sharing app because images and audio files are typically stored in links. I love this idea & I think you should lean into the fact that links are used to store most forms of media so they can really make whatever type of content they'd like


Examples how this format can be used
* Photo Sharing Platform
* Video Streaming Platform
* Audio Streaming Platform
* WebAR Platform
* Coupon Platform
* Software Review Platform
* & the list goes on infinitely 

The core of this idea is sharing links (which is what you expressed in your proposal), but I would lean into the fact that almost all forms of modern media are stored in links.